## S7a — 큐 읽기 전용: 최대 번호 + 스키마 확인 (번호 하드코딩 금지)
ROOT <- Sys.getenv("QM_ROOT", "C:/Users/99922/OneDrive/Quant_Module_Moltbot")
setwd(ROOT)
source("02_Infrastructure/ops/frontier_queue_io.R")
Q <- read_frontier_queue()
cat("top keys:", paste(names(Q), collapse = " | "), "\n")
cat("entries:", length(Q$entries), "\n")
ids <- vapply(Q$entries, function(e) as.character(e$id)[1], character(1))
n <- suppressWarnings(as.integer(sub("^FQ-", "", ids)))
cat("max FQ number:", max(n, na.rm = TRUE), "→ 다음 =", max(n, na.rm = TRUE) + 1L, "\n")
cat("format_ok(무수정 왕복 바이트동일):", frontier_queue_format_ok(), "\n")
cat("--- 최대번호 항목 스키마 ---\n")
str(Q$entries[[which.max(n)]], max.level = 2)
cat("--- 전체 항목에서 관측된 필드명 빈도 ---\n")
fn <- table(unlist(lapply(Q$entries, names)))
print(sort(fn, decreasing = TRUE))
