suppressPackageStartupMessages({ library(data.table) })
setwd("C:/Users/99922/OneDrive/Quant_Module_Moltbot")
A <- readRDS("stage_artifacts/pg2_hunt/factor_long.rds")
M <- readRDS("stage_artifacts/pg2_hunt/mkt.rds")
cat("== factor_long ==\n"); cat("nrow:", nrow(A), "\n"); print(names(A))
cat("Date range:", as.character(min(A$Date)), "-", as.character(max(A$Date)), "\n")
cat("n months:", uniqueN(A$Date), " n factors:", uniqueN(A$Factor_Name), "\n")
cat("day-of-month median:", stats::median(as.integer(format(unique(A$Date), "%d"))), "\n")
cat("== mkt ==\n"); print(names(M)); print(lapply(M, function(x) dim(as.data.table(x))))
r <- as.data.table(M$ret); print(head(r,3)); cat("ret rows:", nrow(r), "na Ret_1m:", sum(is.na(r$Ret_1m)), "\n")
b <- as.data.table(M$bench); print(head(b,3)); cat("bench rows:", nrow(b), "\n")
l <- as.data.table(M$liq); print(head(l,3))
s <- as.data.table(M$size_dt); print(head(s,3))
cat("== FQ191 rule ==\n")
Mru <- fread("stage_artifacts/FQ191/p1_rule.csv")
print(names(Mru)); print(head(Mru,3)); cat("rows:", nrow(Mru), "\n")
Mru[, date := as.Date(date)]
cat("rule range:", as.character(min(Mru$date)), "-", as.character(max(Mru$date)), "\n")
cat("rule dom median:", stats::median(as.integer(format(Mru$date, "%d"))), "\n")
print(table(Mru$regime))
FN <- sort(unique(A$Factor_Name))
mine <- FN[seq_along(FN) %% 8 == 2]
cat("== shard 2 ==\n"); cat("n:", length(mine), "\n"); print(mine)
inc <- NULL
source("02_Infrastructure/contracts/book_marginal.R")
inc <- bm_load_incumbent()
cat("incumbent rows:", nrow(inc), " range:", as.character(min(inc$date)), "-", as.character(max(inc$date)), "\n")
