suppressPackageStartupMessages({ library(data.table) })
setwd("C:/Users/99922/OneDrive/Quant_Module_Moltbot")
A <- readRDS("stage_artifacts/pg2_hunt/factor_long.rds")
M <- readRDS("stage_artifacts/pg2_hunt/mkt.rds")
A <- as.data.table(A)
cat("=== factor_long ===\n")
cat("nrow:", nrow(A), "\n"); cat("cols:", paste(names(A), collapse=","), "\n")
cat("n_factors:", uniqueN(A$Factor_Name), "\n")
cat("n_months:", uniqueN(A$Date), "range:", as.character(min(A$Date)), as.character(max(A$Date)), "\n")
cat("day-of-month median:", stats::median(as.integer(format(unique(A$Date), "%d"))), "\n")
cat("=== mkt ===\n")
cat("names:", paste(names(M), collapse=","), "\n")
for (nm in names(M)) { x <- as.data.table(M[[nm]]); cat(nm, ": nrow", nrow(x), "cols", paste(names(x), collapse=","), "\n") }
r <- as.data.table(M$ret)
cat("ret Date range:", as.character(min(r$Date)), as.character(max(r$Date)), " n_months:", uniqueN(r$Date), "\n")
cat("=== FQ191 rule ===\n")
Mru <- fread("stage_artifacts/FQ191/p1_rule.csv")
cat("cols:", paste(names(Mru), collapse=","), " nrow:", nrow(Mru), "\n")
print(head(Mru, 3)); print(str(Mru))
cat("=== shard ===\n")
FN <- sort(unique(A$Factor_Name))
mine <- FN[seq_along(FN) %% 8 == 0]
cat("shard size:", length(mine), "\n")
cat(paste(mine, collapse="\n"), "\n")
