suppressPackageStartupMessages({library(data.table)})
X <- readRDS(file.path("C:/Users/99922/AppData/Local/Temp/claude/C--Users-99922-OneDrive-Quant-Module-Moltbot/be2e88bf-6a4c-44e5-a6ff-6aae164c14ca/scratchpad/pit_c11/b_data","firstseen.rds"))
fs_ <- X$fs_; rv <- X$rv; options(width=200)
cat("Weekly arrivals (last 5 per series):\n")
print(fs_[Series_ID %in% c("WALCL","NFCI","STLFSI4","ICSA","DEXKOUS"), tail(.SD,5), by=Series_ID][, .(Series_ID, obs=Date, wd=wday(Date), absent_at_or_after=format(avail_lo,"%m-%d %H:%M"), present_by=format(avail_hi,"%m-%d %H:%M"))])
cat("\nDaily last 5 arrivals:\n")
print(fs_[Series_ID %in% c("VIXCLS","DGS10","SP500","BAMLH0A0HYM2"), tail(.SD,5), by=Series_ID][, .(Series_ID, obs=Date, absent_at_or_after=format(avail_lo,"%m-%d %H:%M"), present_by=format(avail_hi,"%m-%d %H:%M"))])
cat("\nRevisions observed across snapshots (07-01~09-24):\n")
print(rv[, .(n_obs_revised=.N, max_abs_rel=round(max(abs(v_last/v_first-1)),5), ex_date=Date[which.max(abs(v_last/v_first-1))], ex_first=v_first[which.max(abs(v_last/v_first-1))], ex_last=v_last[which.max(abs(v_last/v_first-1))]), by=Series_ID])
