library(data.table)
d <- readRDS("C:/Users/99922/OneDrive/Quant_Module_Moltbot/04_Research/strategies/RF_B3_15_SectorNeutral/sector_diag.rds")
cat("months", nrow(d), "\n")
cat("base dist:\n"); print(d[, .N, by = base][order(base)])
cat("S_qualified summary:\n"); print(summary(d$n_sec_qual))
cat("S_all summary:\n"); print(summary(d$n_sec_all))
cat("max_per_sec dist:\n"); print(d[, .N, by = max_per_sec][order(max_per_sec)])
cat("n_sel<25 months:", sum(d$n_sel < 25), "\n")
cat("n_sec_sel summary:\n"); print(summary(d$n_sec_sel))
