## WT-D20260822_004 · P6 — alpha_package.json (AST v1.1 3층 + 완주 설계 4필드) + lineage
suppressPackageStartupMessages({library(data.table); library(arrow); library(jsonlite)})
source("02_Infrastructure/config.R")
OUT <- "stage_artifacts/WT-D20260822_004"; MB <- "qepm/mailbox/worktask/WT-D20260822_004"
V <- readRDS(file.path(OUT,"p4_verdict.rds")); T3 <- readRDS(file.path(OUT,"p3_transport.rds"))
E <- readRDS(file.path(OUT,"p5_emit.rds")); B <- readRDS(file.path(OUT,"p1_arms.rds"))
HY <- fromJSON(file.path(MB,"alpha_hypothesis.json"), simplifyVector = FALSE)
PR <- fromJSON(file.path(OUT,"PREREG.json"), simplifyVector = FALSE)
PRI<-V$PRI; BAS<-V$BAS; ADV<-V$ADV; PERF<-V$PERF
gv <- function(dt,a,c) dt[arm==a][[c]]; pg <- function(a,c) PRI[contrast==a][[c]]
SEL <- HY$selected
live_leaves <- B$sel_rank[[length(B$sel_rank)]]

esc <- function(stat) list(escape_type = "SPECIAL_OP",
  op_code_path = "stage_artifacts/WT-D20260822_004/p1_build_power.R::COMB+build_scores (선별 궤적 승계 = stage_artifacts/WT-D20260822_002/p2_arms_and_gate.R::sel_t+pick, 통계 원자료 = stage_artifacts/WT-D20260813_005/s1_factor_month_stats.rds)",
  walk_forward = TRUE, statistic = stat,
  window_rule = "홀딩월 i 의 선별은 anchor < anchors[i] 인 실현 통계만 소비 (rows (i-36)..(i-1)). MIN_OBS=30 미만 팩터 후보 제외(NA — 0 대입 금지). 결합은 홀딩월 당월 z 만 소비(vintage 이동판 LEAK1/LAG1 은 통제 arm 전용).")

mkfac <- function(id, arm, role, astnode, rule_note, deriv) list(
  factor_id = id, arm = arm, role = role, ast = astnode,
  ast_note = "★AST 는 walk-forward 선별을 정적 리프로 환원할 수 없다 — 선별 집합이 매월 바뀌므로 SPECIAL_OP escape 리프 + escape_contract 로 정직 산출(§4-1 FIELD 리프 위장 금지). 결합 연산자 자체는 𝒪 안에 있다(CS_RANK / CLIP / CS_ZSCORE).",
  combination_within_factor = rule_note,
  selected_leaves_last_holding_month_202607 = live_leaves,
  economic_rationale = deriv,
  redundancy_cluster_id = "FQ244_COMBINATION_RULE",
  redundancy_note = "4 arm 은 의도된 동일-클러스터 대조군 — 재료(320팩터)·창(W=36)·K(5)·선별 궤적·top-N(25)·비용(15bps)이 전부 동일하고 **결합 규칙만** 다르다. 신규 팩터 주장 없음(Factor Zoo 축소 원칙 ① validation > discovery).",
  restatement_exposure = 0)

sp <- function(stat) list(leaf = "SPECIAL_OP", escape_contract = esc(stat))
factors <- list(
  mkfac("FQ244_C0_zscore_ew","C0_zscore_ew","control",
    list(op="CS_ZSCORE", args=list(sp("선별 K=5 팩터의 Z_Score_Aligned 종목별 단순평균 (rowMeans, na.rm)"))),
    "rowMeans(z) — 현행 z_score_aligned_equal_weight. 성분 영향력 비유계.",
    "현행 파이프라인 결합 규칙의 재현 대조군. FQ-237 공표 PORT_t 0.94741072 를 Δ -4.19e-09 로 재현."),
  mkfac("FQ244_C1_rank_avg","C1_rank_avg","treatment_bounded_extreme",
    list(op="CS_ZSCORE", args=list(list(op="CS_RANK", args=list(sp("선별 K=5 팩터 각각의 횡단면 백분위 rank((r-0.5)/n_obs) 후 등가중 평균"))))),
    "rowMeans(pctrank(z)) — 기여 [0,1] 완전 유계, uniform marginal.",
    "승계 기전(alpha_hypothesis): 성분 영향력 유계화의 극한점. 단독 극단 z 의 slot 배분권을 기계적으로 제거해 편입이 다팩터 합의를 요구하게 만든다. 크기 정보는 전량 소거 — C2 와의 대비가 '유계화 vs 크기소거' 를 분리."),
  mkfac("FQ244_C2_winsor_z_ew","C2_winsor_z_ew","treatment_bounded_tail",
    list(op="CS_ZSCORE", args=list(list(op="CLIP", args=list(sp("선별 K=5 팩터의 Z_Score_Aligned"), -2.0, 2.0)))),
    "rowMeans(clip(z, ±2.0)) — c=2.0 단일 사전고정(grid 아님).",
    "승계 기전: 꼬리만 유계화하고 band 내 크기 정보 보존. 예측 gradient = 단독-advocate 억제 C1 ≥ C2 > C0."),
  mkfac("FQ244_C3_max_z","C3_max_z_negctl","negative_control_discriminating",
    list(op="CS_ZSCORE", args=list(sp("선별 K=5 팩터의 Z_Score_Aligned 종목별 최대값 (max_k z_k)"))),
    "max_k(z) — 극단 증폭 결합. ★채택 후보 아님.",
    "판별 arm: 본 기전 참이면 C3 < C0, FQ-116 M2(평균화 뭉갬) 참이면 C3 > C0."))

pkg <- list(
  task_id = "WT-D20260822_004",
  round_id = PR$round_id, fq_ref = "FQ-244",
  as_of_date = "2026-08-22", forecast_horizon = "1M",
  spec_version = "ast_v1.1",
  produced_by = "alpha-research", produced_at = format(Sys.time(), "%Y-%m-%dT%H:%M:%S%z"),
  wt_type = "discovery",
  prereg = "stage_artifacts/WT-D20260822_004/PREREG.json (측정 전 봉인 · entry_gate_order_enforced)",
  pit = list(rules = "C1~C15 적용. 결합은 홀딩월 당월 z, 선별은 anchor < 홀딩 anchor 실현 통계만.",
    C13 = "부호반전 없음 — 전 arm 이 Z_Score_Aligned 입력을 단조·대칭 변환만 한다(rank/clip/max).",
    C15 = "factor DB 직접 load 아님 — 승계 패널 lane_a_feature_panel.parquet(load_month_factors 산출물)."),
  hypothesis = list(
    inherited_from = "qepm/mailbox/worktask/WT-D20260822_004/alpha_hypothesis.json (alpha-hypothesis, model_tier=fable, verdict=designed)",
    inheritance_rule = "Charter 원칙 8 No Silent Override — mechanism / falsification / regime_scope 자구 승계. 결함 발견분은 재작성하지 않고 challenge_note.md 에 기록했다.",
    statement = SEL$hypothesis_description,
    mechanism = SEL$mechanism,
    falsification = SEL$falsification$observable,
    falsification_inherited_verbatim = SEL$falsification,
    regime_scope = SEL$regime_scope),
  factors = factors,
  combination_rule = "z_score_aligned_equal_weight",
  combination_rule_note = "★대조군(C0) 의 enum. 처치 C1 = 'rank_average'(enum 기존재), C2 = z_score_aligned_equal_weight 의 winsorized 입력 변형(enum 밖 — 규칙 자체는 factors[].ast 의 CLIP 노드로 명시), C3 = 음성 대조(enum 밖, 채택 후보 아님). 본 라운드 판정은 **어느 처치도 대조를 개선하지 못했다** 이므로 파이프라인 결합 규칙은 C0 로 불변 유지된다.",
  verdict = "NON_ML_COMBINATION_POWERED_NULL",
  verdict_detail = "비-ML 결합 규칙 2종(C1 rank 평균 · C2 winsor-z 평균)이 C0 대비 IC→PORT_t 전이를 개선하지 못함 — 둘 다 POWERED_NULL_NO_MATERIAL_EFFECT(CI95 상단 +3.01 / +1.49 %p/yr 로 MATERIAL 8.22 배제). 음성 대조 C3(max-z)는 예측대로 유의 악화(t -2.08, EFFECT_NEGATIVE). 기전 귀속: M1 slot 잠식은 실재(R1a 16/25)하나 잠식→손실 링크가 본 풀에 부재(R1b 미수송 + R3 부호역전 t +0.25). 손실 원천은 결합 규칙이 아니라 이산 top-N 소비 마디(FQ-059) 또는 팩터 선택(ORACLE_K 여유폭 4.647 이 선택에 있음). 헌법 재진입 순서 ①(비-ML 먼저) 충족 → ② ML 결합기 자격 발생(별도 사전등록·비-sweep 필요, 단 선택 마디 우선 권고). ★verdict 필드는 라운드 판정이다 — 승계 hypothesis 의 verdict='designed'(hypothesis.inherited_from 에 별도 기록)와 혼동 금지(2026-08-22 alpha-research 자기수정: 초판 p6 가 이 필드에 hypothesis 상태 'designed' 를 전사한 결함을 정정).",
  hypothesis_stage_verdict = "designed (alpha-hypothesis 승계 상태 — 라운드 판정 아님)",
  self_pit_check = list(performed = TRUE, leaves_checked = list(
    list(leaf = "SPECIAL_OP (walk-forward 선별 + 결합)",
         availability_rule = "선별 창이 홀딩 anchor 미만 실현 통계만 소비(rows (i-36)..(i-1)) · 결합은 홀딩월 당월 z. 코드 수준 강제 + vintage 이동 통제 arm(LEAK1 +1M / LAG1 -1M)으로 창 의미 실증.",
         restatement_prone = FALSE),
    list(leaf = "FDB-B6_fdb_daily_store / FDB-B1 / FDB-B2 (factor DB Z_Score_Aligned 320 리프)",
         availability_rule = "load_month_factors() 경유(C15) · 방향정렬 = PIT-safe expanding IC(C13/C14) · 재무 lag = 빌더 규약(C4, 연간 = 익년 3/31)",
         restatement_prone = TRUE),
    list(leaf = "A1_RAWDATA_OHLCVS_daily",
         availability_rule = "price t-1 close · 유동성 자 adv20_t1 (R_LIQ 2e8 재측정에 사용)",
         restatement_prone = FALSE),
    list(leaf = "A4_benchmark_kospi200",
         availability_rule = ".cache/benchmark.parquet 일별 → apply.monthly(Return.cumulative) → ym 조인 (덮개 100%)",
         restatement_prone = FALSE)),
    verdict = "clean",
    notes = "PIT 스트레스 LAG1: PORT_t 0.947 → 0.350, 부호·구조 유지로 붕괴 없음 = 동월 누출 징후 부재. 단 LAG1 paired t -1.47 로 유의 미만이라 이 스트레스의 판별력 자체가 제한적임을 명시(FQ-237 과 같은 한계)."),
  alpha_vector = E$alpha_vector,
  confidence_vector = E$confidence_vector,
  alpha_vector_note = "홀딩월 2026-07 · C0(현행 결합 규칙) 328종목. ★본 라운드는 결합 규칙 변경을 제안하지 않으므로 alpha_vector 는 인컴번트 규칙 산출물이다. confidence = 0.7*(사용팩터수/K) + 0.3*subperiod_stability(3/3 부호 안정).",
  signal_matrix_ref = "stage_artifacts/WT-D20260822_004/alpha_scores.parquet (289,704행 · 221개월 · 4 arm)",
  factor_specs = list(list(
    factor_family = "combination_rule_contrast", proxy = "K=5 selected factor z-composite",
    formula = "C0 rowMeans(z) / C1 rowMeans(pctrank(z)) / C2 rowMeans(clip(z,±2)) / C3 max(z)",
    lag_rule = "선별 anchor < 홀딩 anchor (W=36) · 결합 z = 홀딩월 당월 · 재무 리프는 빌더 C4 규약",
    winsorization = "C2 만 ±2.0 (사전고정 단일값). C0/C1/C3 는 무적용 — 패널 z 는 빌더 단계 처리 승계.",
    neutralization = "미적용 — 승계 자구 유지(중립화 추가는 변형 추가 = sweep 재분류라 사전등록이 금지)",
    economic_rationale = "성분 영향력 유계화가 M1 slot 잠식을 억제해 IC→PORT_t 전이를 개선한다는 승계 기전의 시험. 실측 결과 잠식은 실재(64% slot)하나 손해가 아니어서(R3 t +0.25) 전이 개선 없음.",
    weight_theta = 1.0,
    references = list("FQ-116 / L-AR-20260802_214000 (M1 slot 잠식 기전)",
                      "RAMP R10 / L-RAMP-20260713_084821 (W-factor 성과비례 가중 negative)",
                      "FQ-121 (성분 자격 IS 게이트 config-scoped negative)",
                      "FQ-237 / WT-D20260822_002 (선별 마디 배제 — 본 라운드 출발점)",
                      "Grinold-Kahn TC term / Harvey-Liu-Zhu 2016"))),
  selection_objective = "canonical_port_t",
  selection_objective_note = "iteration/후보 선택 권위 = canonical PORT_t 실측. rank-IC 계열은 advisory. 본 라운드는 argmax 선택 자체가 없다(사전고정 arm 독립 라벨).",
  diagnostics = list(
    canonical_port_t_nw_lag3 = gv(BAS,"C0","port_t_IKS200"),
    canonical_port_t_pvalue  = 0.34342953,
    canonical_n_months = 221,
    canonical_port_t_treatment_C1 = gv(BAS,"C1","port_t_IKS200"),
    canonical_port_t_treatment_C2 = gv(BAS,"C2","port_t_IKS200"),
    canonical_port_t_negctl_C3    = gv(BAS,"C3","port_t_IKS200"),
    canonical_port_t_oracle_node_headroom = gv(BAS,"ORACLE_K","port_t_IKS200"),
    rank_ic = gv(ADV,"C0","rank_ic"), icir = gv(ADV,"C0","icir_monthly"),
    harvey_t_stat = gv(ADV,"C0","harvey_t_rankic_nw3"),
    monotonicity = gv(ADV,"C0","monotonicity"),
    subperiod_stability = 1,
    turnover_proxy = gv(PERF,"C0","turnover"),
    net_sr = gv(PERF,"C0","net_sr"), calmar = gv(PERF,"C0","calmar"), mdd = gv(PERF,"C0","mdd"),
    post_neutralization_ic = NULL,
    post_neutralization_ic_note = "미산출 — 중립화 추가는 변형 추가 = sweep 재분류라 사전등록이 금지했다(승계 자구 유지).",
    metric_type = "canonical_screen",
    ic_vs_port_t_contrast = "★rank-IC Harvey-t 는 C0/C1/C2 전부 2.95 초과(5.30/4.75/5.28)인데 cap-w PORT_t 는 전부 미달(0.947/0.875/0.805). 두 통계량을 명시 구분한다. 본 라운드 추가 관측: 결합 규칙 교체는 **둘 다** 못 움직인다(FQ-237 은 rank-IC 를 움직였으나 PORT_t 가 반대로 갔다)."),
  results = list(
    control_parity = list(measured = gv(BAS,"C0","port_t_IKS200"), published = 0.94741072,
      delta = gv(BAS,"C0","port_t_IKS200")-0.94741072, verdict = "PASS"),
    coprimary = list(
      C1 = list(contrast="C1_rank_avg - C0", n=221, annual_pct=pg("C1","ann_pct"), t_nw3=pg("C1","t_nw3"),
        ci95_annual_pct=c(pg("C1","ci95_lo"), pg("C1","ci95_hi")), mde_annual_pct=3.496,
        label=pg("C1","label"),
        strength="★강한 null — C1 은 매개변수를 실제로 움직였다(solo-advocate 비율 0.688배, 스코어 rank cor 0.911). 처치가 무력해서 나온 null 이 아니다."),
      C2 = list(contrast="C2_winsor_z_ew - C0", n=221, annual_pct=pg("C2","ann_pct"), t_nw3=pg("C2","t_nw3"),
        ci95_annual_pct=c(pg("C2","ci95_lo"), pg("C2","ci95_hi")), mde_annual_pct=2.198,
        label=pg("C2","label"),
        strength="★약한 null — C2 는 매개변수를 유의하게 못 움직였다(0.938배 = R2 NO_MEDIATOR_MOVEMENT, rank cor 0.992). 이 null 은 기전 반증 증거로 약하다. 두 arm 의 null 을 같은 무게로 읽지 말 것.")),
    negative_control_C3 = list(annual_pct=pg("C3","ann_pct"), t_nw3=pg("C3","t_nw3"), label=pg("C3","label")),
    window_reachability = list(
      ORACLE_FWD_port_t = gv(BAS,"ORACLE","port_t_IKS200"),
      ORACLE_K_node_headroom_port_t = gv(BAS,"ORACLE_K","port_t_IKS200"),
      ORACLE_K_paired_annual_pct = pg("ORACLE_K","ann_pct"), ORACLE_K_paired_t = pg("ORACLE_K","t_nw3"),
      material_threshold_annual_pct = V$MATERIAL,
      verdict = "★병기 완료 — 이 창에서 결합 마디는 PORT_t 4.647 까지 도달 가능(ORACLE_K, 벽 2.95 초과)하고 paired 여유폭 +13.69%p/yr(t 4.29)로 MATERIAL 8.22 를 넘는다. ⇒ C1/C2 의 null 은 창이 좁아서가 아니다. '효과없음' 라벨 자격 성립."),
    basis_three_way = list(arm=BAS$arm, port_t_IKS200=BAS$port_t_IKS200,
      port_t_parent_capw=BAS$port_t_parent_capw, port_t_EW_universe=BAS$port_t_EW_universe,
      paired_delta_t = list(C1=-5.551e-17, C2=-1.110e-16, C3=0),
      benchmark_label_caveat = "canonical_screen_bt 의 benchmark_id 는 하드코딩('KOSPI200_total_return'). 실제 계열 = .cache/benchmark.parquet(IKS200) / WT-D20260822_002 p0_returns.rds$bench(parent cap-w) / diag_ew_universe(EW-유니버스)."),
    falsification_measured = list(
      R1a_transport = list(solo_share_median=T3$r1a, threshold=0.20, fired=FALSE,
        verdict="수송 확인 — top-25 의 중앙 16/25 slot 이 solo-advocate 편입. M1 구조 실재."),
      R1b_transfer_negative = list(pool_median=T3$pool_med, solo_median=T3$solo_med, cons_median=T3$cons_med,
        neg_share_solo=T3$neg_share_solo, neg_share_cons=T3$neg_share_cons, fired=TRUE,
        verdict="★미성립 — solo advocate 의 standalone PORT_t 중앙(-0.280)이 풀 중앙(-0.348)보다 높다. FQ-116 의 전이-음성 집중 귀속은 본 풀로 미수송."),
      R2_mediator = list(C1_ratio=median(T3$R$solo_C1)/T3$r1a, C2_ratio=median(T3$R$solo_C2)/T3$r1a,
        C3_ratio=median(T3$R$solo_C3)/T3$r1a, threshold=0.8,
        verdict="C1 통과(0.688) · C2 미통과(0.938, NO_MEDIATOR_MOVEMENT) · C3 증폭(1.312, 설계 의도)"),
      R3_linkage = list(annual_pct=mean(T3$G$gap)*12*100, t_nw3=T3$t_gap, threshold=-1.5,
        fq116_reference=-2.01, fired=TRUE,
        verdict="★연결 절단 — solo 편입이 consensus 편입보다 오히려 연 +1.48%p 더 벌었다(t +0.25). 손실 원천은 slot 잠식이 아니다 → 사전등록대로 이산 top-N 절단 마디(FQ-059)로 귀속 이전."),
      R5_kurtosis = list(iqr_median=T3$r5, threshold=1.0, fired=FALSE,
        verdict="friction3 전제 성립(IQR 6.94) — 꼬리 이질은 실재하나 손실로 연결되지 않았다."),
      coherence="★반증 축이 성과보다 먼저 답했다 — R1b/R3 가 성과 측정 전에 '잠식은 있으나 손해가 아니다' 를 확정했고 primary powered null 이 그와 정합. 사후 해석 아님."),
    controls = list(LEAK1_t=pg("LEAK1","t_nw3"), LEAK1_annual=pg("LEAK1","ann_pct"),
      LAG1_t=pg("LAG1","t_nw3"), LAG1_annual=pg("LAG1","ann_pct"),
      positive_control_prereg_passed = FALSE,
      note="★사전등록 양성 대조 C0_LEAK1 미통과(t +0.67 < 2.0). 정직 진단: z vintage 를 1개월 앞당기는 것은 수익 누출이 아니라 팩터값 갱신이라 약한 개입이다. 창-도달가능성 의무는 ORACLE_K/ORACLE_FWD 로 충족. 부수 정보 = vintage 축 단조성(LAG1 -2.44 / C0 0 / LEAK1 +1.00 %p/yr)으로 하네스가 정보량에 반응함은 실증."),
    redundancy_cross_arm_rank_cor = E$COR),
  labels = list(
    primary_C1 = "POWERED_NULL_NO_MATERIAL_EFFECT (효과없음 — 미결 아님)",
    primary_C2 = "POWERED_NULL_NO_MATERIAL_EFFECT (단 매개 미이동으로 증거력 약함)",
    negative_control_C3 = "EFFECT_NEGATIVE (사전등록 R4 방향 예측 성립)",
    masked_check = "MASKED 아님 — 동시에 반대로 움직인 축 미확인. C3 가 같은 마디에서 유의 음수를 냈으므로 마디 자체는 성과에 반응한다(측정 불능 아님).",
    label_authority = "본 라벨은 canonical_screen 실측 기준. graduation 판정 아님(forge-authoritative 아님)."),
  terminal_form = "alpha_vector",
  terminal_form_note = "결합 결과는 종목별 스코어(=alpha_vector)이며 홀딩월 2026-07 벡터를 328종목으로 발행했다. 다만 본 라운드의 판정은 '결합 규칙을 바꾸지 않는다' 이므로 발행 벡터는 인컴번트 규칙 산출물이고 신규 알파 주장이 아니다.",
  alpha_bridge = list(
    step1 = "factor DB 320 리프 z (Z_Score_Aligned, load_month_factors 승계 패널)",
    step2 = "walk-forward 선별: trailing 36개월 rank-IC 의 NW3 t 상위 K=5 (anchor < 홀딩 anchor)",
    step3 = "결합 규칙 적용 (C0 rowMeans / C1 rank 평균 / C2 clip±2 평균 / C3 max) → 종목별 alpha_score",
    step4 = "alpha_score → top-25 EW long-only, 15bps delta-based, 월간 리밸 (canonical_screen_bt)",
    step5 = "PORT_t(NW lag-3) = 판정 통계량. paired 대조로 결합 규칙 단일 자유도만 이동",
    boundary = "★공분산·weight·최적화 미수행 — top-25 EW 는 고정 규격이지 비중 결정이 아니다(역할 경계 준수)."),
  transition_gates_evaluated = list(
    cond1_alpha_discovery_count = "충족 — alpha_scores.parquet 289,704행 · 221개월 · 4 arm · live 벡터 328종목",
    cond2_screening = "미평가 — 본 라운드 arm 은 자본 후보가 아니라 결합-마디 대조군이다. 참고 실측: C0 net SR 0.228 · CAGR 13.22% · MDD 44.5% · calmar 0.297 (screen_pass 문턱 미달).",
    cond3_falsification_fired = "★2건 발화 — R1b(전이-음성 집중 미성립) + R3(연결 절단). R1a·R5 미발화.",
    cond4_coprimary_supported = "미충족 — SUPPORTED 0건 (C1/C2 둘 다 powered null)",
    decision = "NO_TRANSITION — risk-research 전이 요청하지 않는다. cond4 미충족이며 제안할 결합 규칙 변경이 없다."),
  consumption_gate_precheck = list(
    checked = TRUE,
    consumers = list(
      list(surface="팩터 랭킹(결합 규칙)", status="변경 없음 — C0 유지 확정. 소비면에 밀 산출물 없음."),
      list(surface="유니버스 필터", status="비해당"),
      list(surface="오버레이/국면 입력", status="비해당 — 국면 주장 미승격(R_SUB 는 진단 병기)"),
      list(surface="위험모델·β예산", status="비해당 (역할 경계)"),
      list(surface="monitoring 신호", status="후보 있음 — solo-advocate 편입 비율(월별 중앙 0.64)은 조합 구조 진단지표로 상설화 가능. 단 R3 가 손실 연결을 부정했으므로 경보 지표로는 부적격, 구조 기술통계로만."),
      list(surface="선별 라벨(screen_route)", status="비해당 — 자본 후보 아님"),
      list(surface="타 모드 이식(RAMP/FR)", status="정보 이식 있음 — RAMP R10 W-factor negative 와 본 라운드가 같은 결론('결합/가중 축은 성과-맹목이든 성과-비례든 구속되지 않는다')에 서로 다른 경로로 도달. RAMP 쪽 EW 유지 결정의 독립 재확인.")),
    admission_precheck = "비적용 — book-marginal ΔIR 계산 안 함(제출 후보 없음). governor 정지 불변.",
    verdict = "소비면 7종 순회 완료 — 즉시 소비 가능한 신규 산출물은 없고, 유일한 이식 가치는 'ORACLE_K 여유폭 4.647' 이라는 마디 상한 수치다(다음 라운드 설계 입력)."),
  role_boundary = "alpha-research 경계 준수 — 공분산 추정 0건 / target weights 제안 0건 / 사전 최적화 0건. canonical_screen_bt 의 top-25 EW 는 고정 스크리닝 규격.",
  metric_type = "canonical_screen",
  metric_type_note = "전 수치 canonical_screen_bt() 실측. graduation HARD 3종(PORT_t 2.95 · oos_retention 0.7 · calmar 0.64)은 forge-authoritative 값에만 적용 — 본 패키지 수치로 졸업 주장 금지.",
  selection_type = "preregistered_arms_no_champion",
  sweep_count = 0, n_trials_this_round = 3,
  dsr_note = "DSR HARD 비발동(argmax 선택 부재). 진단값은 alpha_validation.json dsr_diagnostic 참조.",
  challenge_flags = list(
    "[사전등록 양성 대조 미통과] C0_LEAK1 t +0.67 < 2.0 — 창-도달가능성은 ORACLE_K/ORACLE_FWD 로 대체 충족했으나 사전등록 통제 1건이 실패한 사실을 감춘 채 보고하지 않는다.",
    "[승계 기전 부분 반증] R1b·R3 미성립 — FQ-116 의 M1 손실 귀속이 본 팩터 풀로 수송되지 않았다. 승계 자구는 수정하지 않고(Charter 원칙 8) 불일치를 기록한다. 재설계 요청 대상.",
    "[증거력 비대칭] C1 의 null 은 강하고(매개 이동 확인) C2 의 null 은 약하다(매개 미이동). 두 arm 을 '둘 다 null' 로 뭉뚱그리면 과대 주장이다.",
    "[처치 설계 한계] c=2.0 단일점 — 유계화 강도의 용량-반응 미측정(의도적 sweep 회피). C2 의 매개 미이동은 c 가 너무 느슨했을 가능성과 구분되지 않는다.",
    "[국면 caveat] 2015-07 창 분할은 era 교락 + universe_exit_unrecorded_pre201512(편향 하방/중립)와 분리 불가 — 진단 병기만, 국면 주장 미승격.",
    "[선행 약신호] STR_AS_20260613_004517(앙상블 평균법 6종, grade F)는 층·규격이 다르고 batch_434 이명 복제 감사로 코호트 실행-신뢰 훼손 — 약한 사전 음성 신호로만 인지(승계 challenge_flags).",
    "[미측정 축] ORACLE_K 4.647 은 {K개 중 고르기} 족의 상한이지 모든 볼록결합의 상한이 아니다 — 상한 자체가 과소일 수 있으나 결론(여유폭 존재)의 방향은 보수적."),
  next_probe = list(
    list(id="NP1", probe="이산 top-N 절단 마디(FQ-059) — R3 가 손실 원천을 여기로 명시 귀속했다. solo/consensus 편입이 실현수익에서 무차별인데 PORT_t 가 낮다는 것은 손실이 '누구를 넣느냐' 가 아니라 '25개로 자르고 매월 갈아치우는 것'(회전 11.55/yr) 자체에 있을 가능성을 가리킨다. hysteresis/soft-membership paired 측정.",
         why="본 라운드 R3 가 사전등록 문턱으로 귀속을 이전했다"),
    list(id="NP2", probe="결합 마디 여유폭의 도달 경로 — ORACLE_K PORT_t 4.647(paired +13.69%p/yr, t 4.29)이 벽 2.95 를 넘는다. 즉 '어느 팩터를 언제 쓰느냐' 에는 실질 정보가 있다. 단 그 정보를 **trailing 성과**로 예측하는 경로는 RAMP R10(W-factor paired -0.16)과 FQ-121(IS→OOS 부호 반전)이 이미 두 번 죽였다. ⇒ 미측정 경로 = 성과가 아닌 **상태 조건부** 팩터 선택(국면·크라우딩·분산 tercile). v8.4 Lane D 와 직결.",
         why="본 라운드가 마디에 여유폭이 있음을 처음 정량화했고, 동시에 성과-기반 경로가 막혔음을 재확인했다"),
    list(id="NP3", probe="C2 의 용량-반응 — clip c 를 사전등록 단일값으로 한 칸 더 조여(예 c=1.0) 매개변수가 실제로 움직이는지 확인. 본 라운드 C2 의 null 은 매개 미이동과 교락돼 있어 '유계화는 무익' 결론에 C2 를 증거로 쓸 수 없다.",
         why="증거력 비대칭(challenge_flags 3)의 직접 해소"),
    list(id="NP4", probe="solo-advocate 편입 64% 의 의미 재검 — FQ-116 은 다른 풀에서 이 비율이 손실과 연결됐고 여기서는 안 됐다. 두 풀의 차이(고정 5팩터 vs 매월 재선별 K=5)가 무엇을 바꿨는지가 조합 설계 원칙 P1~P4 의 적용 범위를 정한다.",
         why="R1b·R3 미수송의 원인 규명 — FQ-116 설계 원칙의 유효 범위 확정")),
  artifacts = list(
    prereg="stage_artifacts/WT-D20260822_004/PREREG.json",
    scores="stage_artifacts/WT-D20260822_004/alpha_scores.parquet",
    live_vector="stage_artifacts/WT-D20260822_004/alpha_vector_live.parquet",
    validation="stage_artifacts/WT-D20260822_004/alpha_validation.json",
    scripts=c("p0_probe.R","p1_build_power.R","p2_power_gate.R","p3_transport.R","p4_verdict.R","p5_emit.R","p6_alpha_package.R"),
    challenge_note="qepm/mailbox/worktask/WT-D20260822_004/challenge_note.md")
)
write_json(pkg, file.path(MB,"alpha_package.json"), pretty=TRUE, auto_unbox=TRUE, digits=8, na="null")
cat("[alpha_package.json] saved\n")
source("02_Infrastructure/worktask/lineage_utils.R")
record_package_lineage(task_id="WT-D20260822_004", package_type="alpha_package",
  method_selected="FQ-244 비-ML 결합 규칙 4-arm paired (C0 z-EW 대조 / C1 rank평균 / C2 winsor-z / C3 max-z 음성대조)",
  input_file_paths=c("stage_artifacts/fq233_probe0_20260813/lane_a_feature_panel.parquet",
    "stage_artifacts/WT-D20260813_005/s1_factor_month_stats.rds",
    "stage_artifacts/WT-D20260822_002/p2_arms.rds",
    "stage_artifacts/WT-D20260822_002/p0_returns.rds",
    ".cache/benchmark.parquet"))
cat("[lineage] recorded\n")
