suppressPackageStartupMessages({ library(data.table); library(arrow) })
ROOT <- Sys.getenv("QM_ROOT","C:/Users/99922/OneDrive/Quant_Module_Moltbot"); setwd(ROOT)
say <- function(fmt,...) cat(sprintf(paste0("[099] ",fmt,"\n"),...))
D <- as.data.table(read_parquet(".cache/fundamental_merged.parquet"))
say("=== Ticker 형식 x Source ===")
D[, tshape := gsub("[0-9]","#",Ticker)]
print(D[, .N, by=.(Source,tshape)][order(-N)])
say("=== 예시 ===")
for (s in unique(D$Source)) say("  %-13s : %s", s, paste(head(sort(unique(D[Source==s]$Ticker)),5), collapse=" "))
say("=== 티커 집합 겹침 ===")
td <- unique(D[Source=="DART"]$Ticker); tx <- unique(D[Source!="DART"]$Ticker)
say("  DART %d · XLSX계 %d · 교집합 %d", length(td), length(tx), length(intersect(td,tx)))
say("=== RAWDATA 티커 형식 ===")
R <- as.data.table(read_parquet(".cache/rawdata.parquet"))
tr <- unique(R$Ticker)
say("  RAWDATA %d종 예시: %s", length(tr), paste(head(sort(tr),5), collapse=" "))
say("  RAWDATA ∩ DART       = %d", length(intersect(tr, td)))
say("  RAWDATA ∩ XLSX계     = %d", length(intersect(tr, tx)))
