source("02_Infrastructure/config.R")
library(arrow)
library(data.table)
mbs <- as.data.table(read_parquet(".cache/macro_beta_scores.parquet"))
cat("rows:", nrow(mbs), "\n")
cat("cols:", paste(names(mbs), collapse=","), "\n")
cat("class Date:", paste(class(mbs[["Date"]]), collapse=","), "\n")
cat("head Date:", format(head(mbs[["Date"]], 3)), "\n")
cat("unique dates:", length(unique(mbs[["Date"]])), "\n")
cat("unique tickers:", length(unique(mbs[["Ticker"]])), "\n")
cat("NA score:", sum(is.na(mbs[["Score"]])), "\n")
