suppressPackageStartupMessages({library(data.table)})
ROOT <- "C:/Users/99922/OneDrive/Quant_Module_Moltbot"; setwd(ROOT)
OUT <- file.path(ROOT, "stage_artifacts/WT_D20260808_001")
p2 <- readRDS(file.path(OUT, "fq122_part2.rds"))
cat("== fq122_part2 names:", paste(names(p2), collapse=", "), "\n")
cat("\n== F3 (1차 실행) ==\n"); print(p2$F3)
cat("\n== F2 (1차 실행) ==\n"); print(p2$F2)
cat("\n== REG ==\n"); print(p2$REG)
add <- readRDS(file.path(OUT, "wt122_addendum.rds"))
cat("\n== addendum names:", paste(names(add), collapse=", "), "\n")
str(add[grep("F2_size_ctl", names(add))])
ctl <- readRDS(file.path(OUT, "wt122_control.rds"))
cat("\n== control names:", paste(names(ctl), collapse=", "), "\n")
str(ctl, max.level = 2)
res <- readRDS(file.path(OUT, "wt122_results.rds"))
cat("\n== results names:", paste(names(res), collapse=", "), "\n")
cat("\n-- F3 (2차) --\n"); str(res$F3)
cat("\n-- F2 (2차) --\n"); str(res$F2)
