Sys.setenv(LC_ALL = "English_United States.utf8")
suppressWarnings(suppressMessages({ library(data.table); library(arrow) }))
setwd("C:/Users/99922/OneDrive/Quant_Module_Moltbot")
source("02_Infrastructure/config.R")
source("02_Infrastructure/backtest_harness.R")
res <- load_rawdata(use_cache=TRUE); RAWDATA <- res$RAWDATA; BM_DT <- res$BM_DT; rm(res); gc(FALSE)
cat("RAWDATA cols:", paste(names(RAWDATA), collapse=","), "\n")
cat("BM_DT cols:", paste(names(BM_DT), collapse=","), "\n")
cat("has K200:", "K200" %in% names(RAWDATA), " KQ150:", "KQ150" %in% names(RAWDATA), "\n")
cat("RAWDATA class Date:", class(RAWDATA$Date), "\n")
