"""
p1_skewed_t_fit.py — P1 patch v1: Skewed-t fit from LASSO Quantile estimates

Reference:
- Adrian-Boyarchenko-Giannone 2019 AER §III "Vulnerable Growth"
- Azzalini-Capitanio 2003 "Distributions generated by perturbation of symmetry"

Fix to P1 (A LASSO Quantile baseline) issues:
1. var_05 == var_01 (quantile crossing — L1 penalty 부작용)
2. PIT FAIL (분포 모양 부정확)

Approach (Adrian-style):
1. LASSO Quantile에서 11 quantile estimates (τ ∈ {0.01, 0.025, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.975, 0.99})
2. Azzalini-Capitanio skewed-t 4 parameter (μ, σ, ν, ξ) — fit via scipy.optimize least squares to match quantile points
3. fitted skewed-t에서 1000 samples → 정확한 VaR_1%, VaR_5%, P(-X%) 도출

Output:
- var_05 (distinct from var_01)
- var_01
- p_minus_5pct, p_minus_7pct, p_minus_10pct
- skewed-t params (mu, sigma, nu, xi) per obs

Backward compatibility: a1_lasso_quantile.py의 LassoQuantileGaR 직접 사용.
"""
from __future__ import annotations
import numpy as np
from scipy import stats as sp_stats
from scipy import optimize as sp_opt
from typing import Tuple


# Azzalini-Capitanio skewed-t CDF / PDF / quantile
def skew_t_pdf(x, mu, sigma, nu, xi):
    """Fernandez-Steel skewed-t PDF.

    f(x) = (2 / (xi + 1/xi)) * f_t((x-mu)/sigma * xi^(-sign(x-mu)) ; nu) / sigma
    """
    z = (x - mu) / sigma
    sign_z = np.sign(z + 1e-10)
    z_scaled = z * np.power(xi, -sign_z)
    # Student-t standardized pdf
    log_t_kernel = sp_stats.t.logpdf(z_scaled, df=nu)
    log_norm = np.log(2.0 / (xi + 1.0 / xi)) - np.log(sigma)
    return np.exp(log_norm + log_t_kernel)


def skew_t_cdf(x, mu, sigma, nu, xi):
    """Skewed-t CDF — piecewise via Fernandez-Steel decomposition."""
    z = (x - mu) / sigma
    p_right = xi**2 / (xi**2 + 1.0)
    # Left tail (z < 0): F(x) = 2/(xi+1/xi) * xi * F_t(z*xi; nu)
    # Right tail (z > 0): F(x) = p_left + 2/(xi+1/xi) * (1/xi) * (F_t(z/xi; nu) - 0.5)
    # 더 단순: 명시적 mix
    # F_sst(x) = F_t(z*xi; nu) when z < 0 (scaled by mixture weight)
    #          = ... when z > 0
    # Easier: sample-based numeric. For analytical use:
    # F_sst(x) = (2 * xi^2 / (xi^2 + 1)) * F_t(z*xi; nu) for z < 0
    # F_sst(x) = (xi^2 - 1) / (xi^2 + 1) + (2 / (xi^2 + 1)) * F_t(z/xi; nu) for z >= 0
    # (Lambert-Trapletti 2000 표기)
    z = np.atleast_1d(z)
    out = np.empty_like(z, dtype=np.float64)
    mask_left = z < 0
    out[mask_left] = (2.0 * xi**2 / (xi**2 + 1.0)) * sp_stats.t.cdf(z[mask_left] * xi, df=nu)
    out[~mask_left] = (xi**2 - 1.0) / (xi**2 + 1.0) + (2.0 / (xi**2 + 1.0)) * sp_stats.t.cdf(z[~mask_left] / xi, df=nu)
    return out


def skew_t_quantile(p, mu, sigma, nu, xi):
    """Skewed-t inverse CDF (single value or array). Newton-Raphson or numerical."""
    # Use scipy brentq for each p
    p = np.atleast_1d(p).astype(np.float64)
    out = np.empty_like(p)
    for i, p_val in enumerate(p):
        try:
            # Bracket: skewed-t support is (-inf, inf)
            # Use a wide bracket centered at mu, scaled by sigma
            q = sp_opt.brentq(
                lambda x: skew_t_cdf(np.array([x]), mu, sigma, nu, xi)[0] - p_val,
                a=mu - 20 * sigma,
                b=mu + 20 * sigma,
                xtol=1e-6,
            )
        except (ValueError, RuntimeError):
            q = mu + sigma * sp_stats.norm.ppf(p_val)  # fallback Normal
        out[i] = q
    return out


# Fit skewed-t to quantile estimates (Adrian 2019 style)
def fit_skew_t_to_quantiles(
    quantile_values: np.ndarray,
    taus: np.ndarray,
    init_params: Tuple[float, float, float, float] = None,
) -> Tuple[float, float, float, float]:
    """Fit Azzalini-Capitanio skewed-t to n quantile pairs (τ, Q_τ).

    Minimize Σ_τ [F_skew_t^{-1}(τ; μ, σ, ν, ξ) - Q_τ]²

    Args:
        quantile_values: (n_taus,) observed quantile estimates from LASSO
        taus: (n_taus,) tau values
        init_params: (mu, sigma, nu, xi) initial guess

    Returns:
        (mu, sigma, nu, xi) fitted
    """
    if init_params is None:
        mu0 = float(np.median(quantile_values))
        sigma0 = float((np.quantile(quantile_values, 0.84) - np.quantile(quantile_values, 0.16)) / 2)
        sigma0 = max(sigma0, 0.1)
        init_params = (mu0, sigma0, 5.0, 1.0)

    def objective(params):
        mu, log_sigma, log_nu, log_xi = params
        sigma = np.exp(log_sigma)
        nu = 2.5 + np.exp(log_nu)  # nu > 2.5 for finite variance
        xi = np.exp(log_xi)
        q_pred = skew_t_quantile(taus, mu, sigma, nu, xi)
        residuals = q_pred - quantile_values
        return np.sum(residuals ** 2)

    x0 = np.array([
        init_params[0],
        np.log(init_params[1]),
        np.log(init_params[2] - 2.5),
        np.log(init_params[3]),
    ])
    try:
        result = sp_opt.minimize(
            objective, x0, method='Nelder-Mead',
            options={'xatol': 1e-4, 'fatol': 1e-6, 'maxiter': 200},
        )
        mu = result.x[0]
        sigma = np.exp(result.x[1])
        nu = 2.5 + np.exp(result.x[2])
        xi = np.exp(result.x[3])
        return mu, sigma, nu, xi
    except Exception:
        # Fallback Normal
        return init_params


def derive_metrics_from_skew_t(
    quantile_matrix: np.ndarray,  # (N, n_taus)
    taus: np.ndarray,
    n_samples: int = 2000,
    bear_thresholds: Tuple[float, ...] = (-5.0, -7.0, -10.0),
) -> dict:
    """For each observation, fit skewed-t and derive VaR / bear probs.

    Returns:
        dict with arrays per-obs:
            mu, sigma, nu, xi (params)
            var_05, var_01, var_005 (distinct quantiles)
            es_05 (Expected Shortfall)
            p_minus_5, p_minus_7, p_minus_10 (bear probabilities)
    """
    N = quantile_matrix.shape[0]
    mu_arr = np.zeros(N)
    sigma_arr = np.zeros(N)
    nu_arr = np.zeros(N)
    xi_arr = np.zeros(N)
    var_05_arr = np.zeros(N)
    var_01_arr = np.zeros(N)
    var_005_arr = np.zeros(N)
    es_05_arr = np.zeros(N)
    p_neg = {k: np.zeros(N) for k in bear_thresholds}

    for i in range(N):
        Q = np.sort(quantile_matrix[i])
        mu, sigma, nu, xi = fit_skew_t_to_quantiles(Q, taus)
        mu_arr[i] = mu
        sigma_arr[i] = sigma
        nu_arr[i] = nu
        xi_arr[i] = xi
        # Direct quantile derivation
        var_05_arr[i] = skew_t_quantile(np.array([0.05]), mu, sigma, nu, xi)[0]
        var_01_arr[i] = skew_t_quantile(np.array([0.01]), mu, sigma, nu, xi)[0]
        var_005_arr[i] = skew_t_quantile(np.array([0.005]), mu, sigma, nu, xi)[0]
        # Bear probabilities from CDF
        for thr in bear_thresholds:
            p_neg[thr][i] = skew_t_cdf(np.array([thr]), mu, sigma, nu, xi)[0]
        # ES via MC sampling (Adrian-style)
        u = np.random.uniform(0, 1, n_samples)
        samples = skew_t_quantile(u, mu, sigma, nu, xi)
        below = samples < var_05_arr[i]
        if below.any():
            es_05_arr[i] = samples[below].mean()
        else:
            es_05_arr[i] = var_05_arr[i]

    return {
        'mu': mu_arr, 'sigma': sigma_arr, 'nu': nu_arr, 'xi': xi_arr,
        'var_05': var_05_arr, 'var_01': var_01_arr, 'var_005': var_005_arr,
        'es_05': es_05_arr,
        'p_minus_5': p_neg[-5.0],
        'p_minus_7': p_neg[-7.0],
        'p_minus_10': p_neg[-10.0],
    }


def pit_from_skew_t(y_actual: np.ndarray, mu: np.ndarray, sigma: np.ndarray,
                    nu: np.ndarray, xi: np.ndarray) -> np.ndarray:
    """PIT values = F_skew_t(y_actual; μ_t, σ_t, ν_t, ξ_t) per obs."""
    N = len(y_actual)
    pit = np.zeros(N)
    for i in range(N):
        pit[i] = skew_t_cdf(np.array([y_actual[i]]), mu[i], sigma[i], nu[i], xi[i])[0]
    return pit


__all__ = [
    'skew_t_pdf', 'skew_t_cdf', 'skew_t_quantile',
    'fit_skew_t_to_quantiles', 'derive_metrics_from_skew_t',
    'pit_from_skew_t',
]
