suppressMessages({library(arrow);library(data.table);library(dplyr)})
source("02_Infrastructure/factor_db/factor_db_connector.R")
f <- load_month_factors("2015-06-30")
setDT(f)
cat("cols:", paste(names(f),collapse=","), "\n")
nm <- sort(unique(f$Factor_Name))
cat("n_factors:", length(nm), "\n")
cat("M-family:", paste(grep("^M[0-9]", nm, value=TRUE), collapse=" | "), "\n")
cat("L-family:", paste(grep("^L[0-9]", nm, value=TRUE), collapse=" | "), "\n")
cat("n_tickers:", uniqueN(f$Ticker), "\n")
