suppressPackageStartupMessages({ library(data.table) })
ROOT <- Sys.getenv("QM_ROOT","C:/Users/99922/OneDrive/Quant_Module_Moltbot"); setwd(ROOT)
OUT <- file.path(ROOT,"stage_artifacts/fq141_precheck_20260808")
D <- fread(file.path(OUT,"np157c2a1_d_extended.csv")); D[, Date := as.Date(Date)]; setorder(D, Date)
say <- function(fmt,...) cat(sprintf(paste0("[np-c5b] ",fmt,"\n"),...))
say("--- 최근 20개월 월별 d ---")
print(tail(D[, .(Date, d = round(d,5), d_ann_equiv = round(d*12,4))], 20))
say("--- 2025~2026 반기별 ---")
D[, half := paste0(format(Date,"%Y"), ifelse(as.integer(format(Date,"%m"))<=6, "H1","H2"))]
print(D[Date >= as.Date("2024-07-01"), .(n=.N, d_ann=round(mean(d)*12,4)), by=half][order(half)])
say("--- 누적: 언제 정점이었나 (6개월 롤링 d_ann) ---")
n <- nrow(D)
r6 <- rbindlist(lapply(seq(6,n), function(i) data.table(end=D$Date[i], d_ann=mean(D$d[(i-5):i])*12)))
print(tail(r6[, .(end, d_ann=round(d_ann,4))], 14))
