suppressWarnings(suppressMessages({library(data.table); library(arrow)}))
ROOT <- Sys.getenv("QM_ROOT"); if(!nzchar(ROOT)) ROOT <- getwd(); setwd(ROOT)
OUT <- file.path(ROOT,"stage_artifacts/WT_R20260829_004")
P <- readRDS(file.path(OUT,"panel.rds"))
cat("names(P):", paste(names(P),collapse=","), "\n")
D <- as.data.table(P$DAILY); cat("DAILY:", nrow(D), uniqueN(D$Ticker), as.character(min(D$Date)), as.character(max(D$Date)), "\n")
cat("BMD:", nrow(P$BMD), as.character(max(P$BMD$Date)), "\n")
cat("ME n:", length(P$ME), "last:", as.character(tail(P$ME,3)), "\n")
cat("SIZE:", nrow(P$SIZE), paste(names(P$SIZE),collapse=","), "\n")
cat("FACTORS cols:", paste(names(P$FACTORS),collapse=","), "\n")
cat("fwd names:", paste(names(P$fwd),collapse=","), "\n")
print(head(as.data.table(P$fwd$returns_dt),2)); print(head(as.data.table(P$fwd$liq_dt),2))
A <- as.data.table(read_parquet(file.path(OUT,"alpha_scores.parquet")))
cat("alpha_scores months:", uniqueN(A$Date), "last:", as.character(max(A$Date)), "\n")
cat("panic months in scores:", uniqueN(A[panic==1]$Date), "\n")
print(A[Date==max(Date)][order(-score)][1:3])
SG <- as.data.table(read_parquet(file.path(OUT,"regime_signal_timeseries.parquet")))
cat("panic total rows:", sum(SG$panic==1,na.rm=TRUE), "\n")
print(SG[panic==1, .(signal_ym, holding_ym, holding_month_start, used_cutoff)])
