# WT-D20260425_008 Iter 3 Factor Engine Proposal (read-only spec for Forge)
# Generated by Alpha Agent. Forge implements actual engine; do NOT modify.

# Selected 6F PRIMARY: 6F_M08_Residual_Mom
# Replaced: AC21_CF_to_Accrual_Ratio  →  M08_Residual_Mom
# Family: Momentum_Residual
# References: Carhart 1997; Blitz-Huij-Martens 2011; Daniel-Moskowitz 2016

PRIMARY_FACS_ITER3 <- c(
  'C01_SUE',
  'C02_EPS_Chg_1m',
  'C04_ESBR',
  'C06_TP_Gap',
  'Q07_Earnings_Stability',
  'M08_Residual_Mom'
)

# Theta (expanding IC-weighted, last sig_date=2024-01-01):
#   C01_SUE = 0.1863
#   C02_EPS_Chg_1m = 0.1438
#   C04_ESBR = 0.2576
#   C06_TP_Gap = 0.0116
#   M08_Residual_Mom = 0.0401
#   Q07_Earnings_Stability = 0.3606

# Crowding before/after:
#   Q07 ↔ AC21 (baseline) panel cor = 0.0399
#   Q07 ↔ M08_Residual_Mom (Iter 3) panel cor = 0.0099
#   target: < 0.50  | pass: TRUE

# AX-004 evasion: multi-axis composite (Consensus 4F + Q07 + M08_Residual_Mom).
#   single-signal Quality long-only NOT used → AX-004 EXCLUSION clause cleared.

