PROJECT_ROOT <- Sys.getenv("QM_ROOT", "C:/Users/99922/OneDrive/Quant_Module_Moltbot")
Sys.setenv(CLAUDE_PROJECT_DIR = PROJECT_ROOT, QM_ROOT = PROJECT_ROOT)
setwd(PROJECT_ROOT)
suppressPackageStartupMessages({library(data.table); library(arrow)})
source("02_Infrastructure/config.R"); source("02_Infrastructure/backtest_harness.R")
res <- load_rawdata(TRUE); RAWDATA <- res$RAWDATA; rm(res); gc()
tk <- readRDS("04_Research/strategies/RF_B3_12_KOSDAQ_All/tk_labels.rds")
cat("== ticker label counts ==\n"); print(tk[, .N, by=lbl])
cat("\n== Market NA share by YEAR ==\n")
print(RAWDATA[, .(n=.N, na=sum(is.na(Market)), na_share=round(mean(is.na(Market)),3)), by=.(yr=year(Date))][order(yr)])
cat("\n== KQ150==TRUE rows: Market distribution ==\n")
print(RAWDATA[KQ150==TRUE, .N, by=Market])
cat("\n== K200==TRUE rows: Market distribution ==\n")
print(RAWDATA[K200==TRUE, .N, by=Market])
