setwd("C:/Users/99922/OneDrive/Quant_Module_Moltbot")
suppressWarnings(suppressMessages(source("02_Infrastructure/config.R")))
suppressWarnings(suppressMessages(source("02_Infrastructure/factor_db/factor_db_connector.R")))
suppressWarnings(suppressMessages(library(data.table)))
sink("stage_artifacts/WT-D20260813_001/diag_style.txt")
cat("FACTOR_DB_DIR:", FACTOR_DB_DIR, "exists:", dir.exists(FACTOR_DB_DIR), "\n")
fp <- list.files(FACTOR_DB_DIR, pattern="^factor_db_20260[0-9]\\.parquet$|^factor_db_2026(06|07|08)\\.parquet$")
cat("recent files:", paste(fp, collapse=", "), "\n")
r <- tryCatch({
  lf <- load_month_factors(sig_date=as.Date("2026-07-31"),
                           factor_names=c("V01_BM","Q01_GPA","M01_Mom_12_1","D01_IdioVol","L02_Turnover","C01_SUE","V08_PSR"))
  d <- as.data.table(lf)
  cat("nrow", nrow(d), "cols:", paste(names(d), collapse=","), "\n")
  cat("unique Factor_Name:", paste(unique(d$Factor_Name), collapse=","), "\n")
  cat("asof attr:", as.character(attr(lf,"asof_date")), "\n")
  print(d[Ticker %in% c("A000660","A036930")][1:6])
}, error=function(e){ cat("ERR:", conditionMessage(e), "\n"); NULL })
sink()
