setwd("C:/Users/99922/OneDrive/Quant_Module_Moltbot")
p <- jsonlite::fromJSON("qepm/mailbox/worktask/WT-D20260813_001/risk_package.json")
sink("stage_artifacts/WT-D20260813_001/verify.txt")
d <- p$diagnostics
cat("=== DIAGNOSTICS ===\n")
cat(sprintf("vol_a=%.2f%% cond=%.1f(before %.3g) shrink=%s/%s n=%d p=%d\n", d$port_vol_annual_pct, d$condition_number, d$condition_number_before_shrinkage, d$shrinkage_used, d$shrinkage_method, d$n_months_used, d$p_tickers))
cat(sprintf("PC1=%.3f PC1_long=%.3f k=%d common=%.3f specific=%.3f\n", d$pc1_variance_share, d$pc1_variance_share_long_window, d$factor_n, d$common_variance_share, d$specific_variance_share))
cat(sprintf("beta_full=%.3f recent36=%.3f psd=%s min_eig=%.4f\n", d$beta_full, d$beta_recent36, d$psd_verified, d$min_eigenvalue))
cat(sprintf("TDC>0.6=%d hicorr>0.8=%d tdc_basis=%s\n", d$tdc_pairs_gt_0_6, d$high_corr_pairs_gt_0_8, d$tdc_basis))
cat("\n=== STYLE ===\n"); str(d$style_analysis, max.level=2)
cat("\n=== CROWDING per_factor ===\n"); print(p$risk_summary$crowding_score_per_factor)
cat("\n=== STRESS ===\n"); str(p$risk_summary$stress_tests, max.level=2)
cat("\n=== CONCENTRATION ===\n"); print(unlist(p$risk_summary$concentration$sector_weights))
cat(sprintf("sector_hhi=%.3f name_hhi=%.4f n_eff=%.1f\n", p$risk_summary$concentration$sector_hhi, p$risk_summary$concentration$name_hhi, p$risk_summary$concentration$n_eff_names))
cat("\n=== CHALLENGE FLAGS ===\n"); for(f in p$challenge_flags) cat("-",f,"\n")
cat("\n=== CROWDING FLAGS ===\n"); for(f in p$risk_summary$crowding_flags) cat("-",f,"\n")
cat("\n=== TOP COMMON ===\n"); for(f in p$risk_summary$top_common_risks) cat("-",f,"\n")
cat("\n=== TDC top ===\n"); print(d$tdc_top10)
cat("\n=== METHOD LOG ===\n"); print(p$method_shopping_log$risk_agent$method_log)
sink()
