cat("=== STR_1465: L40_VWAP_Spread + Full Construction ===\n")
set.seed(1465); options(scipen=999); Sys.setenv(TZ="Asia/Seoul")
STRATEGY_NAME <- "VWAP_Spread_Const"; STRATEGY_ID <- "STR_1465"; STRATEGY_FAMILY <- "liquidity_construction"
QEPM_AUTO_COMMIT <- TRUE
SCRIPT_DIR <- tryCatch(dirname(sys.frame(1)$ofile), error=function(e) getwd())
INFRA_DIR <- file.path(SCRIPT_DIR, "..", "..", "..", "02_Infrastructure")
if (!file.exists(file.path(INFRA_DIR, "config.R")))
  INFRA_DIR <- file.path(Sys.getenv("CLAUDE_PROJECT_DIR", Sys.getenv("QM_ROOT", "G:/Quant_Module_Moltbot")), "02_Infrastructure")
source(file.path(INFRA_DIR, "config.R"))
source(file.path(INFRA_DIR, "backtest_harness.R"))
library(data.table); library(xts); library(arrow)
tryCatch({ source(file.path(VALIDATION_DIR, "preflight_memory.R")); preflight_check("STR_1465", family="liquidity_construction") }, error=function(e) cat("[Preflight]", e$message, "\n"))
LIQ_THRESHOLD <- 2e8
res <- load_rawdata(use_cache=TRUE); RAWDATA <- res$RAWDATA; BM_DT <- res$BM_DT; RAWDATA_ORIG <- copy(RAWDATA); rm(res); gc(verbose=FALSE)
source(file.path(SCRIPT_DIR, "factor_engine.R"))
stopifnot(is.data.table(FACTORS), all(c("Date","Ticker","Score") %in% names(FACTORS)), nrow(FACTORS) > 0)
RAWDATA <- copy(RAWDATA_ORIG)
sim_base <- run_monthly_simulation(RAWDATA=RAWDATA, BM_DT=BM_DT, FACTORS=FACTORS, n_holdings=30L, weight_method="equal", commission=0.0015, buffer_zone=list(keep_n=50L, entry_n=25L))
raw_ret <- as.numeric(sim_base$strategy_xts); raw_dates <- as.Date(index(sim_base$strategy_xts)); n_f <- length(raw_ret)
nav_dd <- cumprod(1+raw_ret); dd_pct <- 1-nav_dd/cummax(nav_dd)
DD_START <- 10/100; DD_FULL <- 0.20; DD_MIN_EXP <- 0.30
dd_pct_lagged <- c(0, dd_pct[-n_f])
dd_exp_lagged <- fifelse(dd_pct_lagged<=DD_START, 1.0, fifelse(dd_pct_lagged>=DD_FULL, DD_MIN_EXP, pmax(DD_MIN_EXP, 1.0-(dd_pct_lagged-DD_START)/(DD_FULL-DD_START)*(1-DD_MIN_EXP))))
final_ret <- raw_ret * dd_exp_lagged
combined_xts <- xts(final_ret, order.by=raw_dates); names(combined_xts) <- "Strategy"
sim <- sim_base; sim$strategy_xts <- combined_xts; sim$bm_xts <- sim_base$bm_xts[raw_dates]
sim$DAILY_NAV_DT <- data.table(Date=raw_dates, NAV=cumprod(1+final_ret)*10000, Strategy_Ret=final_ret)
output_dir <- file.path(SCRIPT_DIR, "output"); dir.create(output_dir, showWarnings=FALSE, recursive=TRUE)
perf_strat <- summarise_perf(sim$strategy_xts, "VWAP_Spread_Const"); perf_bm <- summarise_perf(sim$bm_xts, "BM")
cat(sprintf("  %s: CAGR=%.2f%% SR=%.3f MDD=%.1f%%\n", "STR_1465", perf_strat$CAGR, perf_strat$Sharpe, perf_strat$MDD))
generate_charts(sim, output_dir=output_dir, strategy_name="VWAP_Spread_Const")
fwrite(rbind(perf_strat, perf_bm), file.path(output_dir, "performance.csv"))
saveRDS(sim, file.path(output_dir, "sim_result.rds")); saveRDS(sim, file.path(SCRIPT_DIR, "sim_result.rds"))
RAWDATA <- copy(RAWDATA_ORIG)
tryCatch({ source(file.path(INFRA_DIR, "strategy_analyzer.R")); run_analysis(sim, FACTORS, RAWDATA, BM_DT, output_dir, strategy_name="STR_1465") }, error=function(e) cat("[WARN]", e$message, "\n"))
source(file.path(INFRA_DIR, "hurdle_gate.R"))
hurdle <- run_hurdle_gate(sim_result=sim, FACTORS=FACTORS, strategy_name="VWAP_Spread_Const", strategy_file=file.path(SCRIPT_DIR,"factor_engine.R"), output_dir=output_dir)
jsonlite::write_json(hurdle, file.path(output_dir, "hurdle_result.json"), auto_unbox=TRUE, pretty=TRUE)
cat(sprintf("  Grade: %s Score: %.1f\n", hurdle$grade, hurdle$total_score %||% hurdle$score %||% 0))
tryCatch({ source(file.path(TELEGRAM_DIR, "telegram_notify.R")); hr <- jsonlite::fromJSON(file.path(output_dir, "hurdle_result.json")); tg_strategy_result_with_chart("STR_1465", hr, output_dir) }, error=function(e) cat("[TG]", e$message, "\n"))
if (isTRUE(QEPM_AUTO_COMMIT)) tryCatch({ qh <- file.path(dirname(dirname(dirname(SCRIPT_DIR))), "qepm", "scripts", "hybrid_mode.R"); if(file.exists(qh)) { source(qh); if(exists("hybrid_commit")) hybrid_commit(strategy_name="STR_1465", family="liquidity_construction", hurdle_result=hurdle, artifact_paths=list(output_dir)) } }, error=function(e) cat("[QEPM]", e$message, "\n"))
cat(sprintf("=== %s Complete ===\n", "STR_1465"))
