suppressPackageStartupMessages(library(jsonlite))
ROOT <- "C:/Users/99922/OneDrive/Quant_Module_Moltbot"; setwd(ROOT)
h <- fromJSON("qepm/mailbox/worktask/WT-D20260808_001/alpha_hypothesis.json", simplifyVector=FALSE)
cat("== selected keys ==\n"); cat(paste(names(h$selected), collapse=", "), "\n")
cat("== handoff keys ==\n"); cat(paste(names(h$handoff), collapse=", "), "\n")
str(h$selected, max.level=2, list.len=40)
cat("\n== handoff ==\n"); str(h$handoff, max.level=3, list.len=40)
cat("\n== 원문에 'F4'/'킬스위치'/'reject_if' 문자열 존재? ==\n")
txt <- paste(capture.output(str(h, max.level=8, list.len=200)), collapse="\n")
raw <- readLines("qepm/mailbox/worktask/WT-D20260808_001/alpha_hypothesis.json", warn=FALSE)
one <- paste(raw, collapse="\n")
for (k in c("F4","킬스위치","reject_if","falsification","반증","rank 20","20~40","좌측")) {
  cat(sprintf("  '%s' : %d 회\n", k, lengths(regmatches(one, gregexpr(k, one, fixed=TRUE)))))
}
cat("\n== preregistration selection_type / dsr ==\n")
pr <- fromJSON("stage_artifacts/WT_D20260808_001/preregistration.json", simplifyVector=FALSE)
for (k in c("written_at","written_before","selection_type","n_trials","dsr_gate_applicable","dsr_gate_rationale","capital_claim","inherited_from_hypothesis_agent")) {
  cat(sprintf("  %s = %s\n", k, substr(paste(unlist(pr[[k]]), collapse=" | "), 1, 500)))
}
cat("\n== novelty_control_mandate ==\n")
cat(substr(paste(unlist(pr$novelty_control_mandate), collapse=" | "), 1, 800), "\n")
cat("\n== hard_axes_fixed ==\n")
cat(substr(paste(unlist(pr$hard_axes_fixed), collapse=" | "), 1, 800), "\n")
cat("\n== addendum sign_agreement_gate / positive_claim_requires_all ==\n")
pa <- fromJSON("stage_artifacts/WT_D20260808_001/preregistration_addendum.json", simplifyVector=FALSE)
cat("sign_gate:", substr(paste(unlist(pa$sign_agreement_gate), collapse=" | "),1,600), "\n")
cat("positive_all:", substr(paste(unlist(pa$positive_claim_requires_all), collapse=" | "),1,600), "\n")
cat("harm:", substr(paste(unlist(pa$harm_claim_requires), collapse=" | "),1,400), "\n")
cat("otherwise:", substr(paste(unlist(pa$otherwise), collapse=" | "),1,400), "\n")
