suppressWarnings(suppressMessages({library(data.table)}))
ROOT <- Sys.getenv("QM_ROOT"); if (!nzchar(ROOT)) ROOT <- getwd(); setwd(ROOT)
Sys.setenv(CLAUDE_PROJECT_DIR = ROOT)
source(file.path(ROOT, "02_Infrastructure/factor_db/factor_db_connector.R"))
t0 <- Sys.time()
x <- as.data.table(load_month_factors(as.Date("2018-06-29"), factor_names = c("L01_Amihud","L09_Amihud_20d","L11_Kyle_Lambda","D35_RealVol_63d","M06_High_52w","M17_Low_52w","M07_IndMom","M02_Mom_6_1")))
cat("elapsed:", as.numeric(difftime(Sys.time(), t0, units="secs")), "s  rows:", nrow(x), "\n")
cat("cols:", paste(names(x), collapse=", "), "\n")
print(x[, .N, by = Factor_Name])
