suppressWarnings(suppressMessages({library(data.table); library(arrow); library(jsonlite)}))
ROOT <- Sys.getenv("QM_ROOT"); if(!nzchar(ROOT)) ROOT <- getwd(); setwd(ROOT)
OUT <- file.path(ROOT,"stage_artifacts/WT_R20260829_007")
A <- as.data.table(read_parquet(file.path(OUT,"alpha_scores.parquet")))
cat("alpha_scores cols:", paste(names(A),collapse=", "), "\n")
cat("nrow:", nrow(A), " dates:", length(unique(A$Date)), " range:", as.character(min(A$Date)), as.character(max(A$Date)), "\n")
print(head(A,3))
cat("\n--- top25 per date summary ---\n")
print(A[, .(n=.N, ntop=sum(in_top25, na.rm=TRUE)), by=Date][order(Date)][c(1:3, .N-2, .N-1, .N)])
cat("\n--- period_returns_production ---\n")
PR <- fread(file.path(OUT,"period_returns_production.csv"))
cat("cols:", paste(names(PR),collapse=", "),"\n"); print(head(PR,3)); cat("nrow", nrow(PR), "\n")
cat("\n--- panel.rds ---\n")
pn <- readRDS(file.path(OUT,"panel.rds"))
cat("names(pn):", paste(names(pn),collapse=", "),"\n")
for(nm in names(pn)){ x<-pn[[nm]]; cat(" ",nm,":", class(x)[1], if(is.list(x)&&!is.data.frame(x)) paste0("[",paste(names(x),collapse=","),"]") else paste(dim(x),collapse="x"), "\n")}
