suppressMessages(library(jsonlite))
p <- fromJSON("qepm/mailbox/worktask/WT-R20260829_007/alpha_package.json", simplifyVector=FALSE)
cat("=== handoff_to_risk ===\n")
cat(toJSON(p$handoff_to_risk, auto_unbox=TRUE, pretty=TRUE))
cat("\n=== factor_specs ===\n")
cat(substr(toJSON(p$factor_specs, auto_unbox=TRUE, pretty=TRUE),1,4000))
cat("\n=== signal_matrix_ref ===\n"); print(p$signal_matrix_ref)
cat("=== validation_ref ===\n"); print(p$validation_ref)
cat("=== diagnostics names ===\n"); print(names(p$diagnostics))
cat("=== selection_objective / n_trials / selection_type ===\n")
print(c(p$selection_objective, p$n_trials, p$selection_type))
