suppressMessages(library(jsonlite))
p <- fromJSON("qepm/mailbox/worktask/WT-R20260829_007/risk_package.json", simplifyVector=FALSE)
cat("keys:",paste(names(p),collapse=", "),"\n")
cat("methods_tried n =", length(p$diagnostics$methods_tried), "(limit 5)\n")
cat("crowding_score_per_factor n =", length(p$risk_summary$crowding_score_per_factor), "\n")
cat("condition_number =", p$diagnostics$condition_number, " before =", p$diagnostics$condition_number_before_shrinkage,"\n")
cat("market_down_5 =", p$risk_summary$stress_tests$market_down_5, "\n")
cat("challenge_flags n =", length(p$challenge_flags),"\n")
cat("file size:", file.size("qepm/mailbox/worktask/WT-R20260829_007/risk_package.json"), "bytes\n")
t <- fromJSON("stage_artifacts/WT_R20260829_007/tail_risk.json", simplifyVector=FALSE)
cat("tail keys:",paste(names(t),collapse=", "),"\n")
