cat("=== STR_1622: S3 Orthogonality Analysis ===\n")
## 핵심아이디어: IC-Weighted Statistical Blend (C19+V14+Q01+D01+M25) 직교성 검증

options(scipen=999); Sys.setenv(TZ="Asia/Seoul")
set.seed(1622)

INFRA_DIR  <- "/mnt/c/Users/User/OneDrive/\ubc14\ud0d5 \ud654\uba74/Quant_Module_Moltbot/02_Infrastructure"
STRAT_DIR  <- "/mnt/c/Users/User/OneDrive/\ubc14\ud0d5 \ud654\uba74/Quant_Module_Moltbot/research_output/strategies/STR_1622_ic_weighted_statistical_blend"
STRATEGY_ID <- "STR_1622"
FACTOR_ID   <- "C19+V14+Q01+D01+M25_IC_Weighted"

suppressPackageStartupMessages({
  library(data.table)
  library(jsonlite)
  library(arrow)
  library(dplyr)
})

source(file.path(INFRA_DIR, "config.R"))
source(file.path(INFRA_DIR, "backtest_harness.R"))
source(file.path(INFRA_DIR, "factor_research_pipeline.R"))

FACTOR_REG_PATH <<- file.path(INFRA_DIR, "factor_db", "factor_registry.json")
cat(sprintf("FACTOR_REG_PATH override: %s (exists=%s)\n", FACTOR_REG_PATH, file.exists(FACTOR_REG_PATH)))

cat("Loading RAWDATA...\n")
res <- load_rawdata(use_cache = TRUE)
RAWDATA <- res$RAWDATA
BM_DT   <- res$BM_DT
RAWDATA_ORIG <- copy(RAWDATA)
rm(res); gc(verbose = FALSE)

cat("Sourcing factor_engine.R...\n")
source(file.path(STRAT_DIR, "factor_engine.R"))
FACTOR_REG_PATH <<- file.path(INFRA_DIR, "factor_db", "factor_registry.json")

if (!exists("FACTORS") || is.null(FACTORS) || nrow(FACTORS) == 0) {
  stop("FACTORS not generated by factor_engine.R")
}

last_date <- max(FACTORS$Date)
cat(sprintf("Using sig_date: %s | n rows: %d\n", last_date, nrow(FACTORS[Date == last_date])))

new_z <- FACTORS[Date == last_date, setNames(Score, Ticker)]
new_z <- new_z[!is.na(new_z)]
cat(sprintf("n tickers in new_z: %d\n", length(new_z)))

cat("Calling compute_factor_orthogonality...\n")
orth <- compute_factor_orthogonality(new_z, last_date, active_only = TRUE)
cat(sprintf("max_corr: %.4f | max_corr_factor: %s | independence: %s | n_compared: %d\n",
            orth$max_corr, orth$max_corr_factor, orth$independence, orth$n_compared))

s3_verdict <- if (orth$independence == "independent") "PASS" else if (orth$independence == "partial") "PASS_PARTIAL" else "FAIL_REDUNDANT"

top5 <- head(orth$pairwise_corr[order(-abs(orth$pairwise_corr$Corr)), ], 5)

s3_artifact <- list(
  strategy_id     = STRATEGY_ID,
  factor_id       = FACTOR_ID,
  stage           = "S3",
  generated_at    = format(Sys.Date()),
  sig_date        = format(last_date),
  max_corr        = round(orth$max_corr, 4),
  max_corr_factor = orth$max_corr_factor,
  independence    = orth$independence,
  n_compared      = orth$n_compared,
  s3_verdict      = s3_verdict,
  top5_corr       = lapply(seq_len(nrow(top5)), function(i)
    list(Factor_Name = top5$Factor_Name[i], Corr = round(top5$Corr[i], 4))),
  note            = "5-factor IC-weighted blend. High overlap expected with STR_1621 due to shared C19+V14+D01 components."
)

out_path <- file.path(STRAT_DIR, "stage_artifacts", sprintf("s3_orthogonality_%s.json", STRATEGY_ID))
write_json(s3_artifact, out_path, auto_unbox = TRUE, pretty = TRUE)
cat(sprintf("S3 artifact written: %s\n", out_path))
cat(sprintf("VERDICT: %s | max_corr=%.4f | independence=%s\n", s3_verdict, orth$max_corr, orth$independence))
