setwd("C:/Users/99922/OneDrive/Quant_Module_Moltbot")
options(stringsAsFactors = FALSE)
p0 <- readRDS("stage_artifacts/FQ182/p0.rds")
cat("=== p0 object names ===\n"); print(names(p0))
D <- p0$D
cat("=== class ===\n"); print(class(D))
cat("=== dim ===\n"); print(dim(D))
cat("=== colnames ===\n"); print(colnames(D))
cat("=== head 3 ===\n"); print(utils::head(as.data.frame(D), 3))
cat("=== tail 3 ===\n"); print(utils::tail(as.data.frame(D), 3))
cat("=== Date range ===\n"); print(range(D$Date))
cat("=== NA per col ===\n"); print(sapply(as.data.frame(D), function(x) sum(is.na(x))))
cat("=== BM_Ret summary ===\n"); print(summary(D$BM_Ret))
cat("=== sd BM_Ret ===\n"); print(sd(D$BM_Ret, na.rm=TRUE))
cat("=== dd252 range ===\n"); print(range(D$dd252, na.rm=TRUE))
cat("=== observation unit check: median day gap ===\n")
print(summary(as.numeric(diff(as.Date(D$Date)))))
cat("=== n distinct dates ===\n"); print(length(unique(D$Date)))
