setwd("C:/Users/99922/OneDrive/Quant_Module_Moltbot/04_Research/meta/axiom_replay")
source("R/build_world.R")
led <- ar_load_ledger(1); att <- ar_attempts_df(led); ent <- ar_entries_df(led, att)
ws <- ar_build_worlds(ent, att)
cat("트리:", length(ws), "\n")
nd <- do.call(rbind, lapply(ws, function(w) cbind(base_id = w$base_id, w$nodes)))
cat("노드:", nrow(nd), " 측정:", sum(nd$evaluated), "\n\n=== 바닥 감사 ===\n")
print(sort(table(sub(":.*$", "", nd$floor_audit)), decreasing = TRUE))
cat("\n=== 블록별 감사(비-B1) ===\n")
print(table(nd$block[nd$block != "B1"], sub(":.*$", "", nd$floor_audit[nd$block != "B1"])))
cat("\n=== 실패 분류 ===\n"); print(sort(table(nd$fail_class), decreasing = TRUE))
cat("\n=== 배치 크기 분포 ===\n"); print(table(table(paste(nd$base_id, nd$batch))))
saveRDS(ws, "out/worlds.rds")
