#!/usr/bin/env Rscript
# =============================================================================
# Strategy Template v2.0 — Auto-generated by Forge Agent
# =============================================================================
# This template is populated by Forge (agent_forge.R) with hypothesis-specific
# values before execution. Forge replaces {{PLACEHOLDERS}} with actual logic.
#
# Compatible with the research orchestrator pipeline:
#   Q-Lead -> Forge (fills template) -> execute -> Judge (validates)
#
# Usage (by Forge):
#   1. Copy to 04_Research/strategies/STR_XXXX_<slug>/run_all.R
#   2. Replace {{PLACEHOLDERS}} with hypothesis-specific values
#   3. Generate factor_engine.R alongside
#   4. Execute: cd strategy_dir && Rscript -e 'source("run_all.R")'
#
# Manual usage:
#   cd "strategy_dir" && Rscript -e 'source("run_all.R")'
#
# Placeholders reference:
#   {{STRATEGY_ID}}    — e.g., "STR_1039"
#   {{STRATEGY_NAME}}  — e.g., "Regime_Alloc_DynWeight"
#   {{FAMILY}}         — e.g., "regime_alloc"
#   {{HYPOTHESIS}}     — 1-sentence hypothesis text
#   {{BUCKET}}         — exploit / stabilize / explore / diagnose
#   {{SEED}}           — integer seed (e.g., 1039)
#   {{TIMESTAMP}}      — ISO timestamp of generation
#   {{N_HOLDINGS}}     — integer, 10-30
#   {{WEIGHT_METHOD}}  — equal / inverse_vol / risk_parity
#   {{KEEP_N}}         — buffer zone keep_n (e.g., 40)
#   {{ENTRY_N}}        — buffer zone entry_n (e.g., 20)
#   {{VOL_TARGET}}     — numeric or NULL (e.g., 0.18)
#   {{DD_BRAKE}}       — numeric or NULL (e.g., 0.04)
# =============================================================================

## {{STRATEGY_ID}}: {{STRATEGY_NAME}}
## Family: {{FAMILY}}
## Hypothesis: {{HYPOTHESIS}}
## Bucket: {{BUCKET}} (exploit/stabilize/explore/diagnose)
## Auto-generated: {{TIMESTAMP}}

# ---- Step 0: Environment ----
set.seed({{SEED}}); options(scipen = 999); Sys.setenv(TZ = "Asia/Seoul")
STRATEGY_NAME   <- "{{STRATEGY_NAME}}"
STRATEGY_ID     <- "{{STRATEGY_ID}}"
STRATEGY_FAMILY <- "{{FAMILY}}"
QEPM_AUTO_COMMIT <- TRUE

cat(sprintf("=== %s: %s ===\n", STRATEGY_ID, STRATEGY_NAME))
cat("## Hypothesis: {{HYPOTHESIS}}\n")

# ---- Path resolution (Korean path safe) ----
SCRIPT_DIR <- tryCatch({
  d <- dirname(sys.frame(1)$ofile)
  if (d == ".") getwd() else d
}, error = function(e) {
  args <- commandArgs(trailingOnly = FALSE)
  file_arg <- grep("--file=", args, value = TRUE)
  if (length(file_arg) > 0) {
    p <- sub("--file=", "", file_arg[1])
    p <- gsub("~+~", " ", p, fixed = TRUE)
    dirname(p)
  } else getwd()
})

INFRA_DIR <- file.path(dirname(dirname(dirname(SCRIPT_DIR))), "02_Infrastructure")
if (!file.exists(file.path(INFRA_DIR, "config.R"))) {
  INFRA_DIR <- file.path(
    Sys.getenv("CLAUDE_PROJECT_DIR", Sys.getenv("QM_ROOT", "G:/Quant_Module_Moltbot")),
    "02_Infrastructure"
  )
}

# ---- Step 1: Load infrastructure ----
source(file.path(INFRA_DIR, "config.R"))
source(file.path(INFRA_DIR, "backtest_harness.R"))
source(file.path(TELEGRAM_DIR, "telegram_notify.R"))

# Preflight check (PIT memory + L-code dedup)
tryCatch({
  source(file.path(VALIDATION_DIR, "preflight_memory.R"))
  preflight_check(STRATEGY_ID, family = STRATEGY_FAMILY)
}, error = function(e) cat("[Preflight]", e$message, "\n"))

cat(sprintf("\n=== %s: %s ===\n\n", STRATEGY_ID, STRATEGY_NAME))

# ---- Production constraints ----
LIQ_THRESHOLD  <- 2e8      # 20-day avg trading value >= 2 billion KRW
N_HOLDINGS     <- {{N_HOLDINGS}}
WEIGHT_METHOD  <- "{{WEIGHT_METHOD}}"
COMMISSION     <- 0.0015   # 15 bps round-trip (commission + slippage)
BUFFER_ZONE    <- list(keep_n = {{KEEP_N}}L, entry_n = {{ENTRY_N}}L)

# Overlays (t-1 lag enforced for PIT compliance: C2/C5/C9)
VOL_TARGET      <- {{VOL_TARGET}}     # Annual vol target (NULL to disable)
VOL_LOOKBACK    <- 60L               # Trading days for expanding vol estimation
DD_BRAKE_THRESH <- {{DD_BRAKE}}       # Drawdown threshold (NULL to disable)

# =============================================================================
# Step 2: Load data
# =============================================================================
cat("[Step 2] Loading data...\n")
res <- load_rawdata(use_cache = TRUE)
RAWDATA <- res$RAWDATA; BM_DT <- res$BM_DT
rm(res); gc(verbose = FALSE)

# Liquidity filter (C10: must use lagged trading value, not same-day)
cat(sprintf("[Step 2] Liquidity filter (20d avg >= %.0f billion KRW)...\n", LIQ_THRESHOLD / 1e8))
RAWDATA[, TradingValue := Close * Vol]
RAWDATA[, AvgTV20 := frollmean(TradingValue, n = 20L, align = "right"), by = Ticker]
RAWDATA[, LiqPass := !is.na(AvgTV20) & AvgTV20 >= LIQ_THRESHOLD]

cat(sprintf("  Data: %s ~ %s | %d tickers | %d rows\n",
            min(RAWDATA$Date), max(RAWDATA$Date),
            uniqueN(RAWDATA$Ticker), nrow(RAWDATA)))

# =============================================================================
# Step 3: Factor construction
# =============================================================================
cat("[Step 3] Constructing factors...\n")

# --- Factor Engine v3 규칙 (2026-03-24 강화) ---
# Forge generates factor_engine.R with hypothesis-specific factor logic.
# MUST produce: FACTORS data.table with columns Date, Ticker, Score
#
# ===== MANDATORY PIT RULES (C1~C15) =====
#   C1:  No full-sample stats. Expanding/rolling only.
#   C2:  No same-day circular. VT/DD/FM = t-1.
#   C4:  Financial statement: annual→May, quarterly→45d lag.
#   C5:  Overlay signals use t-1.
#   C10: Liquidity filter: AvgTV20 shift(lag=1).
#   C11: Data time axis: FRED 1d lag, ECOS same-day OK.
#   C13: 수동 방향 반전 금지! NEGATE_FACTORS/FLIP_SIGN 사용 금지.
#        Factor DB 사용 시 반드시 factor_db_connector.R의 Z_Score_Aligned만 사용.
#   C14: IC 접근 시 Usable_Date <= sig_date만 허용.
#        IC[Date <= sig_d]는 1개월 미래참조!
#   C15: Factor DB parquet 직접 로드 금지.
#        반드시 load_month_factors(sig_date) 사용.
#
# Factor DB 사용 시 표준 패턴:
#   source(file.path(FACTOR_DB_DIR, "factor_db_connector.R"))
#   fdt <- load_month_factors(sig_date)  # Z_Score_Aligned 반환
#   ic  <- compute_rolling_ic_all(sig_date)  # Usable_Date 기반

FACTOR_ENGINE_PATH <- file.path(SCRIPT_DIR, "factor_engine.R")
if (file.exists(FACTOR_ENGINE_PATH)) {
  source(FACTOR_ENGINE_PATH)
} else {
  stop("[FATAL] factor_engine.R not found in ", SCRIPT_DIR,
       "\nForge must generate this file alongside run_all.R")
}

# Validate FACTORS output
if (exists("FACTORS") && is.data.table(FACTORS)) {
  stopifnot(all(c("Date", "Ticker", "Score") %in% names(FACTORS)))
  cat(sprintf("  FACTORS: %d rows | %d signal dates | %d unique tickers\n",
              nrow(FACTORS), uniqueN(FACTORS$Date), uniqueN(FACTORS$Ticker)))
} else if ("FACTORS" %in% names(RAWDATA)) {
  # Factor engine attached scores directly to RAWDATA
  cat(sprintf("  FACTORS attached to RAWDATA: %d non-NA scores\n",
              sum(!is.na(RAWDATA$FACTORS))))
} else {
  stop("[FATAL] Neither FACTORS data.table nor RAWDATA$FACTORS column found.")
}

# =============================================================================
# Step 4: Lookahead detection (C1~C11)
# =============================================================================
cat("[Step 4] Lookahead detection...\n")
tryCatch({
  source(file.path(VALIDATION_DIR, "lookahead_detector.R"))
  pit_result <- detect_lookahead(FACTOR_ENGINE_PATH)
  if (!isTRUE(pit_result$clean)) {
    cat("[PIT VIOLATION] Lookahead detected in factor_engine.R:\n")
    for (v in pit_result$violations) {
      cat(sprintf("  Line %d [%s]: %s\n", v$line, v$check, v$msg))
    }
    stop("PIT violation detected. Aborting backtest.")
  }
  cat("  PIT check: CLEAN\n")
}, error = function(e) {
  if (grepl("PIT violation", e$message)) stop(e)
  cat("[WARN] Lookahead detector:", e$message, "\n")
})

# =============================================================================
# Step 5: Backtest simulation
# =============================================================================
cat("[Step 5] Running monthly simulation...\n")
cat(sprintf("  N=%d, weight=%s, commission=%.4f\n", N_HOLDINGS, WEIGHT_METHOD, COMMISSION))
if (!is.null(VOL_TARGET)) cat(sprintf("  Vol target: %.0f%%, lookback: %dd\n", VOL_TARGET * 100, VOL_LOOKBACK))
if (!is.null(DD_BRAKE_THRESH)) cat(sprintf("  DD brake threshold: %.1f%%\n", DD_BRAKE_THRESH * 100))

# Determine FACTORS argument based on what factor_engine.R produced
factors_arg <- if (exists("FACTORS") && is.data.table(FACTORS)) {
  FACTORS
} else {
  RAWDATA$FACTORS
}

sim <- tryCatch({
  run_monthly_simulation(
    RAWDATA     = RAWDATA,
    BM_DT       = BM_DT,
    FACTORS     = factors_arg,
    n_holdings  = N_HOLDINGS,
    weight_method = WEIGHT_METHOD,
    commission  = COMMISSION,
    buffer_zone = BUFFER_ZONE,
    vol_target  = VOL_TARGET,
    vol_lookback = VOL_LOOKBACK
  )
}, error = function(e) {
  cat("[FATAL] Simulation failed:", e$message, "\n")
  stop(e)
})

cat(sprintf("  Simulation: %d trading days\n", length(sim$strategy_xts)))

# =============================================================================
# Step 6: Analysis
# =============================================================================
cat("[Step 6] Running analysis...\n")
OUTPUT_DIR <- file.path(SCRIPT_DIR, "output")
dir.create(OUTPUT_DIR, recursive = TRUE, showWarnings = FALSE)

# Strategy analyzer (produces analysis_ic.csv, analysis_multifactor.csv, charts)
tryCatch({
  source(file.path(INFRA_DIR, "strategy_analyzer.R"))
  run_analysis(sim, factors_arg, RAWDATA, BM_DT, OUTPUT_DIR,
               strategy_name = STRATEGY_ID)
}, error = function(e) {
  cat("[WARN] strategy_analyzer:", e$message, "\n")
  # Fallback: minimal performance summary
  tryCatch({
    perf <- summarise_perf(sim$strategy_xts, STRATEGY_NAME)
    fwrite(perf, file.path(OUTPUT_DIR, "performance.csv"))
  }, error = function(e2) NULL)
})

# =============================================================================
# Step 7: Hurdle Gate evaluation
# =============================================================================
cat("[Step 7] Hurdle gate...\n")
tryCatch({
  source(file.path(INFRA_DIR, "hurdle_gate.R"))
  hurdle <- run_hurdle_gate(
    sim_result    = sim,
    FACTORS       = factors_arg,
    strategy_name = STRATEGY_NAME,
    strategy_file = FACTOR_ENGINE_PATH,
    output_dir    = OUTPUT_DIR
  )

  cat(sprintf("\n  Grade: %s | Score: %.1f | Verdict: %s\n",
              hurdle$grade,
              hurdle$total_score %||% hurdle$score %||% 0,
              if (isTRUE(hurdle$pass)) "PASS" else "FAIL"))

  # Save hurdle result
  jsonlite::write_json(hurdle, file.path(OUTPUT_DIR, "hurdle_result.json"),
                       auto_unbox = TRUE, pretty = TRUE)

  # Save sim result
  saveRDS(sim, file.path(SCRIPT_DIR, "sim_result.rds"))

  # Telegram: chart + result
  tryCatch({
    tg_strategy_result_with_chart(
      strategy_name = STRATEGY_ID,
      hurdle_result = hurdle,
      output_dir    = OUTPUT_DIR
    )
  }, error = function(e) {
    tryCatch(tg_strategy_result(STRATEGY_ID, hurdle), error = function(e2) NULL)
  })

  # QEPM auto-commit (hybrid_commit handles R0~R4 + Registry + L-code)
  if (isTRUE(QEPM_AUTO_COMMIT)) {
    tryCatch({
      if (exists("hybrid_commit")) {
        hybrid_commit(
          strategy_name  = STRATEGY_ID,
          family         = STRATEGY_FAMILY,
          hurdle_result  = hurdle,
          artifact_paths = list(OUTPUT_DIR)
        )
      }
    }, error = function(e) cat("[QEPM] auto-commit failed:", e$message, "\n"))
  }

}, error = function(e) {
  cat("[ERROR] Hurdle gate failed:", e$message, "\n")
  # Save partial results
  tryCatch(saveRDS(sim, file.path(SCRIPT_DIR, "sim_result.rds")), error = function(e2) NULL)
})

cat(sprintf("\n=== %s Complete ===\n", STRATEGY_ID))
