suppressMessages(library(jsonlite))
rp <- fromJSON("qepm/mailbox/worktask/WT-D20260802_003/risk_package.json", simplifyVector=FALSE)
req <- c("task_id","as_of_date","factor_covariance_ref","risk_summary","diagnostics","challenge_flags")
cat("required fields present:", all(req %in% names(rp)), "\n")
cat("cap_tier_decomposition present:", !is.null(rp$risk_summary$cap_tier_decomposition), "\n")
cat("divergence_flag:", rp$risk_summary$cap_tier_decomposition$dual_basis_divergence_flag, "\n")
cat("crowding rows:", length(rp$risk_summary$crowding_score_per_factor), "\n")
cat("cond:", rp$diagnostics$condition_number, "(before", rp$diagnostics$condition_number_before_floor, ")\n")
cat("n challenge flags:", length(rp$challenge_flags), "\n")
