suppressMessages({library(data.table)})
setwd("C:/Users/99922/OneDrive/Quant_Module_Moltbot/04_Research/factor_rotation/fof_first_slice")
ec<-readRDS("_wt_eval_canonical.rds");ea<-readRDS("_wt_eval_allliq.rds")
dc<-readRDS("_wt_diag_canonical.rds");da<-readRDS("_wt_diag_allliq.rds")
pr<-function(r)sprintf("port_t=%.2f IR=%.2f netSR=%.2f 2022+=%.2f oos=%.2f calmar=%.2f MDD=%.1f%% turn=%.0f%%",
  r$port_t,r$IR,r$net_sr,r$t_2022,r$oos_ret,r$calmar,100*r$mdd,100*r$turnover)
cat("CANON ENS:",pr(ec$canonical_ENSEMBLE),"\n")
cat("CANON seeds port_t:",paste(round(sapply(ec[grepl("^canonical",names(ec))&!grepl("ENS",names(ec))],function(x)x$port_t),2),collapse=","),"\n")
cat("ALLLIQ ENS:",pr(ea$allliq_ENSEMBLE),"\n")
cat("ALLLIQ seeds port_t:",paste(round(sapply(ea[grepl("^allliq",names(ea))&!grepl("ENS",names(ea))],function(x)x$port_t),2),collapse=","),"\n")
cat(sprintf("CANON diag: rankIC=%.4f ICIR=%.2f IC_t_NW=%.2f placebo_p=%.3f bonf_p=%.2g\n",dc$ic_mean,dc$icir,dc$ic_t_nw,dc$placebo_p,dc$hlz_p_bonf))
cat(sprintf("ALLLIQ diag: rankIC=%.4f ICIR=%.2f IC_t_NW=%.2f placebo_p=%.3f bonf_p=%.2g\n",da$ic_mean,da$icir,da$ic_t_nw,da$placebo_p,da$hlz_p_bonf))
# per-seed 2022+ / oos
cat("CANON seed 2022+:",paste(round(sapply(ec[grepl("^canonical",names(ec))&!grepl("ENS",names(ec))],function(x)x$t_2022),2),collapse=","),"\n")
cat("CANON seed oos:",paste(round(sapply(ec[grepl("^canonical",names(ec))&!grepl("ENS",names(ec))],function(x)x$oos_ret),2),collapse=","),"\n")
cat("ALLLIQ seed 2022+:",paste(round(sapply(ea[grepl("^allliq",names(ea))&!grepl("ENS",names(ea))],function(x)x$t_2022),2),collapse=","),"\n")
cat("ALLLIQ seed oos:",paste(round(sapply(ea[grepl("^allliq",names(ea))&!grepl("ENS",names(ea))],function(x)x$oos_ret),2),collapse=","),"\n")
al<-readRDS("_wt_alpha.rds")
cat(sprintf("ALPHA: beta_mean=%.4f beta_lb=%.4f k=%.1f slope_t=%.2f latest=%s N=%d\n",al$beta_mean,al$beta_lb,al$k_shrink,al$beta_mean/al$beta_se,al$latest,al$n_names))
