suppressMessages({library(arrow); library(data.table)})
setDTthreads(1)
sink("stage_artifacts/WT-D20260621_009/_inspect.txt")
sb <- as.data.table(read_parquet(".cache/stock_buyback.parquet"))
cat("=== stock_buyback ===\n"); print(names(sb)); cat("rows:", nrow(sb), "\n")
print(head(sb,3)); cat("nonzero frac:", mean(sb$Value!=0,na.rm=T), " negatives:", sum(sb$Value<0,na.rm=T), "\n")
cat("Period sample:", head(unique(as.character(sb$Period)),3), "...\n")
cat("Factor_Date class:", class(sb$Factor_Date), " range:", as.character(range(sb$Factor_Date,na.rm=T)),"\n")
cat("Period_Date class:", class(sb$Period_Date),"\n")
bm <- as.data.table(read_parquet(".cache/benchmark.parquet"))
cat("\n=== benchmark ===\n"); print(names(bm)); print(head(bm,2)); cat("rows:",nrow(bm),"\n")
kf <- as.data.table(read_parquet(".cache/kr_factor_returns_v2.parquet"))
cat("\n=== kr_factor_returns_v2 ===\n"); print(names(kf)); cat("rows:",nrow(kf),"\n"); print(head(kf,2))
sink()
cat("DONE\n")
