library(arrow)
library(data.table)
PROJ <- Sys.getenv("CLAUDE_PROJECT_DIR", "C:/Users/99922/OneDrive/Quant_Module_Moltbot")
fred <- as.data.table(read_parquet(file.path(PROJ, ".cache/fred_macro.parquet")))
cat("Columns:", paste(names(fred), collapse=", "), "\n")
cat("Nrow:", nrow(fred), "\n")
cat("Date range:", as.character(min(fred$Date)), "to", as.character(max(fred$Date)), "\n")
series_summary <- unique(fred[, .(Series, Series_ID, Frequency)])
cat("\nAll Series:\n")
print(series_summary)
target_series <- c("Term_Spread", "VIX", "KRW_USD", "HY_Spread")
cat("\nTarget present:", paste(target_series[target_series %in% series_summary$Series], collapse=", "), "\n")
cat("Target missing:", paste(target_series[!target_series %in% series_summary$Series], collapse=", "), "\n")
# check Series_ID
target_ids <- c("T10Y2Y", "VIXCLS", "DEXKOUS", "BAMLH0A0HYM2")
cat("\nTarget Series_ID present:", paste(target_ids[target_ids %in% series_summary$Series_ID], collapse=", "), "\n")
cat("Target Series_ID missing:", paste(target_ids[!target_ids %in% series_summary$Series_ID], collapse=", "), "\n")
# sample a few rows
cat("\nSample rows:\n")
print(head(fred[Series %in% c("Term_Spread","VIX","KRW_USD","HY_Spread")], 20))
